In [110]:
# Import Dependenices.
import pandas as pd

# Import Meteostat library and dependencies.
from datetime import datetime
from datetime import time
import matplotlib.pyplot as plt
from meteostat import Point, Daily

In [111]:
# Read the California Fire Incidents CSV file into Pandas DataFrame.
fire_incidents_df = pd.read_csv("Resources/California_Fire_Incidents.csv")
fire_incidents_df

,AcresBurned,Active,AdminUnit,AirTankers,ArchiveYear,CalFireIncident,CanonicalUrl,ConditionStatement,ControlStatement,Counties,...,SearchKeywords,Started,Status,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,UniqueId,Updated,WaterTenders
0,257314.0,False,Stanislaus National Forest/Yosemite National Park,NaN,2013,True,/incidents/2013/8/17/rim-fire/,NaN,NaN,Tuolumne,...,"Rim Fire, Stanislaus National Forest, Yosemite...",2013-08-17T15:25:00Z,Finalized,NaN,NaN,NaN,NaN,5fb18d4d-213f-4d83-a179-daaf11939e78,2013-09-06T18:30:00Z,NaN
1,30274.0,False,USFS Angeles National Forest/Los Angeles Count...,NaN,2013,True,/incidents/2013/5/30/powerhouse-fire/,NaN,NaN,Los Angeles,...,"Powerhouse Fire, May 2013, June 2013, Angeles ...",2013-05-30T15:28:00Z,Finalized,NaN,NaN,NaN,NaN,bf37805e-1cc2-4208-9972-753e47874c87,2013-06-08T18:30:00Z,NaN
2,27531.0,False,CAL FIRE Riverside Unit / San Bernardino Natio...,NaN,2013,True,/incidents/2013/7/15/mountain-fire/,NaN,NaN,Riverside,...,"Mountain Fire, July 2013, Highway 243, Highway...",2013-07-15T13:43:00Z,Finalized,NaN,NaN,NaN,NaN,a3149fec-4d48-427c-8b2c-59e8b79d59db,2013-07-30T18:00:00Z,NaN
3,27440.0,False,Tahoe National Forest,NaN,2013,False,/incidents/2013/8/10/american-fire/,NaN,NaN,Placer,...,"American Fire, August 2013, Deadwood Ridge, Fo...",2013-08-10T16:30:00Z,Finalized,NaN,NaN,NaN,NaN,8213f5c7-34fa-403b-a4bc-da2ace6e6625,2013-08-30T08:00:00Z,NaN
4,24251.0,False,Ventura County Fire/CAL FIRE,NaN,2013,True,/incidents/2013/5/2/springs-fire/,Acreage has been reduced based upon more accur...,NaN,Ventura,...,"Springs Fire, May 2013, Highway 101, Camarillo...",2013-05-02T07:01:00Z,Finalized,6.0,10.0,NaN,NaN,46731fb8-3350-4920-bdf7-910ac0eb715c,2013-05-11T06:30:00Z,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,9.0,False,CAL FIRE / Riverside County Fire,NaN,2019,True,/incidents/2019/10/10/eagle-fire/,NaN,NaN,Riverside,...,NaN,2019-10-10T12:08:00Z,Finalized,NaN,NaN,NaN,NaN,6e93b252-99a3-4214-9921-238373b17535,2019-10-10T18:11:59.733Z,NaN
1632,2.0,False,CAL FIRE Nevada-Yuba-Placer Unit,NaN,2019,True,/incidents/2019/6/28/long-fire/,NaN,NaN,Nevada,...,NaN,2019-06-28T15:03:04Z,Finalized,NaN,NaN,NaN,NaN,b38c0563-b321-431b-9174-6336c5a0d449,2019-06-30T15:52:01.023Z,NaN
1633,NaN,False,Yolo County Fire Protection District,NaN,2019,False,/incidents/2019/11/25/cashe-fire/,NaN,NaN,Yolo,...,NaN,2019-11-25T12:02:02Z,Finalized,NaN,NaN,NaN,NaN,9c26f915-1b33-422d-b30a-9eb4da6fd729,2019-12-03T16:35:20.93Z,NaN
1634,NaN,False,Camp Pendleton Marine Corps Base,NaN,2019,False,/incidents/2019/10/22/oak-fire/,NaN,NaN,San Diego,...,NaN,2019-10-22T19:20:44Z,Finalized,NaN,NaN,NaN,NaN,7264a106-e0f4-41de-8fd0-3f9110431e28,2019-11-21T12:21:28.58Z,NaN
1635,NaN,False,Bureau of Indian Affairs,NaN,2019,False,/incidents/2019/10/14/johnson-fire/,"As of 10:00 p.m. on 10/16, the fire is 90% con...",NaN,Riverside,...,NaN,2019-10-14T15:32:20Z,Inactive,NaN,NaN,NaN,NaN,8bf75401-999f-42bd-8c0a-8db508591545,2019-10-30T10:14:19.58Z,NaN

In [112]:
# Check the data types of the California Fire Incidents DataFrame columns.
fire_incidents_df.dtypes

AcresBurned             float64
Active                     bool
AdminUnit                object
AirTankers              float64
ArchiveYear               int64
CalFireIncident            bool
CanonicalUrl             object
ConditionStatement       object
ControlStatement         object
Counties                 object
CountyIds                object
CrewsInvolved           float64
Dozers                  float64
Engines                 float64
Extinguished             object
Fatalities              float64
Featured                   bool
Final                      bool
FuelType                 object
Helicopters             float64
Injuries                float64
Latitude                float64
Location                 object
Longitude               float64
MajorIncident              bool
Name                     object
PercentContained        float64
PersonnelInvolved       float64
Public                     bool
SearchDescription        object
SearchKeywords           object
Started                  object
Status                   object
StructuresDamaged       float64
StructuresDestroyed     float64
StructuresEvacuated     float64
StructuresThreatened    float64
UniqueId                 object
Updated                  object
WaterTenders            float64
dtype: object

In [113]:
# Convert the "Started" and "Extinguished" columns into date datatype.
fire_incidents_df["Started"] = pd.to_datetime(fire_incidents_df["Started"])
fire_incidents_df["Extinguished"] = pd.to_datetime(fire_incidents_df["Extinguished"])

In [114]:
# Split the date and time and keep the dates.
fire_incidents_df["Start_Date"] = [d.date() for d in fire_incidents_df["Started"]]
fire_incidents_df["End_Date"] = [d.date() for d in fire_incidents_df["Extinguished"]]

In [115]:
# Keep the required columns.
fire_incidents_df = fire_incidents_df[["AcresBurned", "ArchiveYear", "Counties", "CountyIds", "Start_Date", "End_Date", "Injuries", "Latitude", "Longitude", "MajorIncident", "Location", "Name", "PercentContained", "StructuresDamaged", "StructuresDestroyed", "StructuresEvacuated", "StructuresThreatened"]]
fire_incidents_df.head()

,AcresBurned,ArchiveYear,Counties,CountyIds,Start_Date,End_Date,Injuries,Latitude,Longitude,MajorIncident,Location,Name,PercentContained,StructuresDamaged,StructuresDestroyed,StructuresEvacuated,StructuresThreatened
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,NaN,37.857000,-120.086000,False,3 miles east of Groveland along Hwy 120,Rim Fire,100.0,NaN,NaN,NaN,NaN
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,NaN,34.585595,-118.423176,False,Angeles National Forest,Powerhouse Fire,100.0,NaN,NaN,NaN,NaN
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,NaN,33.709500,-116.728850,False,Hwy 243 & Hwy 74 near Mountain Center,Mountain Fire,100.0,NaN,NaN,NaN,NaN
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,NaN,39.120000,-120.650000,False,"Deadwood Ridge, northeast of Foresthill",American Fire,100.0,NaN,NaN,NaN,NaN
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.000000,0.000000,True,Southbound Highway 101 at Camarillo Springs Ro...,Springs Fire,100.0,6.0,10.0,NaN,NaN

In [116]:
# Read the California Fire Perimeters CSV file into Pandas DataFrame.
fire_perimeters_df = pd.read_csv("Resources/California_Fire_Perimeters.csv")
fire_perimeters_df.head()

,OBJECTID,YEAR_,STATE,AGENCY,UNIT_ID,FIRE_NAME,INC_NUM,ALARM_DATE,CONT_DATE,CAUSE,COMMENTS,REPORT_AC,GIS_ACRES,C_METHOD,OBJECTIVE,FIRE_NUM,SHAPE_Length,SHAPE_Area
0,21440,2020.0,CA,CDF,NEU,NELSON,00013212,2020/06/18 00:00:00+00,2020/06/23 00:00:00+00,11.0,NaN,110.0,109.60250,1.0,1.0,NaN,4179.743142,7.331347e+05
1,21441,2020.0,CA,CDF,NEU,AMORUSO,00011799,2020/06/01 00:00:00+00,2020/06/04 00:00:00+00,2.0,NaN,670.0,685.58502,1.0,1.0,NaN,12399.375391,4.578172e+06
2,21442,2020.0,CA,CDF,NEU,ATHENS,00018493,2020/08/10 00:00:00+00,2020/03/01 00:00:00+00,14.0,NaN,26.0,27.30048,1.0,1.0,NaN,2119.194120,1.823876e+05
3,21443,2020.0,CA,CDF,NEU,FLEMING,00007619,2020/03/31 00:00:00+00,2020/04/01 00:00:00+00,9.0,NaN,13.0,12.93155,1.0,1.0,NaN,2029.524881,8.667942e+04
4,21444,2020.0,CA,CDF,NEU,MELANESE,00008471,2020/04/14 00:00:00+00,2020/04/19 00:00:00+00,18.0,NaN,10.3,10.31596,1.0,1.0,NaN,1342.742903,7.017912e+04

In [117]:
# Check the datatypes of California Fire Perimeters DataFrame columns.
fire_perimeters_df.dtypes

OBJECTID          int64
YEAR_           float64
STATE            object
AGENCY           object
UNIT_ID          object
FIRE_NAME        object
INC_NUM          object
ALARM_DATE       object
CONT_DATE        object
CAUSE           float64
COMMENTS         object
REPORT_AC       float64
GIS_ACRES       float64
C_METHOD        float64
OBJECTIVE       float64
FIRE_NUM         object
SHAPE_Length    float64
SHAPE_Area      float64
dtype: object

In [118]:
# Convert the "ALARM_DATE" and "CONT_DATE" columns into date datatype.
fire_perimeters_df["ALARM_DATE"] = pd.to_datetime(fire_perimeters_df['ALARM_DATE'], errors='coerce')
fire_perimeters_df["CONT_DATE"] = pd.to_datetime(fire_perimeters_df['CONT_DATE'], errors='coerce')

In [119]:
# Split the date and time and keep the dates.
fire_perimeters_df['Start_Date'] = [d.date() for d in fire_perimeters_df['ALARM_DATE']]
fire_perimeters_df['End_Date'] = [d.date() for d in fire_perimeters_df['CONT_DATE']]

In [120]:
# Keep the required columns.
fire_perimeters_df = fire_perimeters_df[['YEAR_', 'STATE','FIRE_NAME', 'Start_Date', 'End_Date', 'CAUSE', 'SHAPE_Length', 'SHAPE_Area', 'GIS_ACRES']]
fire_perimeters_df

,YEAR_,STATE,FIRE_NAME,Start_Date,End_Date,CAUSE,SHAPE_Length,SHAPE_Area,GIS_ACRES
0,2020.0,CA,NELSON,2020-06-18,2020-06-23,11.0,4179.743142,7.331347e+05,109.602500
1,2020.0,CA,AMORUSO,2020-06-01,2020-06-04,2.0,12399.375391,4.578172e+06,685.585020
2,2020.0,CA,ATHENS,2020-08-10,2020-03-01,14.0,2119.194120,1.823876e+05,27.300480
3,2020.0,CA,FLEMING,2020-03-31,2020-04-01,9.0,2029.524881,8.667942e+04,12.931550
4,2020.0,CA,MELANESE,2020-04-14,2020-04-19,18.0,1342.742903,7.017912e+04,10.315960
...,...,...,...,...,...,...,...,...,...
21313,2019.0,CA,MUREAU,2019-10-30,2019-10-30,NaN,897.323534,3.730642e+04,6.297734
21314,2019.0,CA,OAK,2019-10-28,2019-10-28,14.0,1215.382952,5.024716e+04,8.482671
21315,2019.0,CA,BARHAM,2019-11-09,2019-11-10,14.0,4093.657796,3.843117e+05,64.888229
21316,2019.0,CA,STAR,NaT,NaT,14.0,4777.042672,4.051741e+05,66.587181
21317,2019.0,CA,SADDLE RIDGE,2019-10-10,2019-10-31,14.0,86547.407832,5.233553e+07,8799.325200

In [121]:
fire_perimeters_df["CAUSE"].isnull().sum()

48

In [122]:
# Merge fire incident and fire perimeter DataFrames.
california_fire = fire_incidents_df.merge(fire_perimeters_df, how="left", on=["Start_Date", "End_Date"])
california_fire.columns

Index(['AcresBurned', 'ArchiveYear', 'Counties', 'CountyIds', 'Start_Date',
       'End_Date', 'Injuries', 'Latitude', 'Longitude', 'MajorIncident',
       'Location', 'Name', 'PercentContained', 'StructuresDamaged',
       'StructuresDestroyed', 'StructuresEvacuated', 'StructuresThreatened',
       'YEAR_', 'STATE', 'FIRE_NAME', 'CAUSE', 'SHAPE_Length', 'SHAPE_Area',
       'GIS_ACRES'],
      dtype='object')

In [123]:
california_fire

,AcresBurned,ArchiveYear,Counties,CountyIds,Start_Date,End_Date,Injuries,Latitude,Longitude,MajorIncident,...,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,YEAR_,STATE,FIRE_NAME,CAUSE,SHAPE_Length,SHAPE_Area,GIS_ACRES
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,NaN,37.857000,-120.086000,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,NaN,34.585595,-118.423176,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,NaN,33.709500,-116.728850,False,...,NaN,NaN,NaN,2013.0,CA,MOUNTAIN,9.0,95986.473341,1.614355e+08,27523.666000
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,NaN,39.120000,-120.650000,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.000000,0.000000,True,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,9.0,2019,Riverside,33,2019-10-10,2019-10-10,NaN,33.827979,-117.499619,False,...,NaN,NaN,NaN,2019.0,CA,PLAINS,10.0,3400.679987,2.954705e+05,42.175037
1730,2.0,2019,Nevada,29,2019-06-28,2019-06-28,NaN,39.409722,-121.000556,False,...,NaN,NaN,NaN,2019.0,CA,BUENA,8.0,491.662839,1.027569e+04,1.671938
1731,NaN,2019,Yolo,57,2019-11-25,NaT,NaN,38.734634,-121.729691,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1732,NaN,2019,San Diego,37,2019-10-22,NaT,NaN,33.351145,-117.403719,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1733,NaN,2019,Riverside,33,2019-10-14,NaT,NaN,33.451480,-116.058980,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [124]:
#Replacing all nulls for the cause column with unidentified (14)
california_fire["CAUSE"] = california_fire["CAUSE"].fillna(14.0)

In [125]:
california_fire

,AcresBurned,ArchiveYear,Counties,CountyIds,Start_Date,End_Date,Injuries,Latitude,Longitude,MajorIncident,...,StructuresDestroyed,StructuresEvacuated,StructuresThreatened,YEAR_,STATE,FIRE_NAME,CAUSE,SHAPE_Length,SHAPE_Area,GIS_ACRES
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,NaN,37.857000,-120.086000,False,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,NaN,34.585595,-118.423176,False,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,NaN,33.709500,-116.728850,False,...,NaN,NaN,NaN,2013.0,CA,MOUNTAIN,9.0,95986.473341,1.614355e+08,27523.666000
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,NaN,39.120000,-120.650000,False,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.000000,0.000000,True,...,10.0,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,9.0,2019,Riverside,33,2019-10-10,2019-10-10,NaN,33.827979,-117.499619,False,...,NaN,NaN,NaN,2019.0,CA,PLAINS,10.0,3400.679987,2.954705e+05,42.175037
1730,2.0,2019,Nevada,29,2019-06-28,2019-06-28,NaN,39.409722,-121.000556,False,...,NaN,NaN,NaN,2019.0,CA,BUENA,8.0,491.662839,1.027569e+04,1.671938
1731,NaN,2019,Yolo,57,2019-11-25,NaT,NaN,38.734634,-121.729691,False,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
1732,NaN,2019,San Diego,37,2019-10-22,NaT,NaN,33.351145,-117.403719,False,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN
1733,NaN,2019,Riverside,33,2019-10-14,NaT,NaN,33.451480,-116.058980,False,...,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN

In [126]:
#Changing the data type for cause column from float to integer 
california_fire["CAUSE"] = california_fire["CAUSE"].astype(int)

In [127]:
# Create a new DataFrame for the cause column.
d= {'CAUSE': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], 'Cause_Description': ['Lightning', 'Equipment Use', 'Smoking', 'Campfire', 'Debris', 'Railroad', 'Arson', 'Playing with fire', 'Miscellaneous', 'Vehicle', 'Powerline', 'Figherfighter Training', 'Non-Firefighter Training', 'Unidentified', 'Structure', 'Aircraft','Unidentified', 'Escaped Prescribed Burn', 'Illegal Alien Campfire']}

fire_cause = pd.DataFrame(data=d)
fire_cause

    CAUSE         Cause_Description
0       1                 Lightning
1       2             Equipment Use
2       3                   Smoking
3       4                  Campfire
4       5                    Debris
5       6                  Railroad
6       7                     Arson
7       8         Playing with fire
8       9             Miscellaneous
9      10                   Vehicle
10     11                 Powerline
11     12    Figherfighter Training
12     13  Non-Firefighter Training
13     14              Unidentified
14     15                 Structure
15     16                  Aircraft
16     17              Unidentified
17     18   Escaped Prescribed Burn
18     19    Illegal Alien Campfire

In [128]:
# Merge fire cause description with the main dataframe.
california_fire = california_fire.merge(fire_cause, how='left', on="CAUSE")
california_fire.head()

,AcresBurned,ArchiveYear,Counties,CountyIds,Start_Date,End_Date,Injuries,Latitude,Longitude,MajorIncident,...,StructuresEvacuated,StructuresThreatened,YEAR_,STATE,FIRE_NAME,CAUSE,SHAPE_Length,SHAPE_Area,GIS_ACRES,Cause_Description
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,NaN,37.857000,-120.086000,False,...,NaN,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN,Unidentified
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,NaN,34.585595,-118.423176,False,...,NaN,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN,Unidentified
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,NaN,33.709500,-116.728850,False,...,NaN,NaN,2013.0,CA,MOUNTAIN,9,95986.473341,1.614355e+08,27523.666,Miscellaneous
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,NaN,39.120000,-120.650000,False,...,NaN,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN,Unidentified
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.000000,0.000000,True,...,NaN,NaN,NaN,NaN,NaN,14,NaN,NaN,NaN,Unidentified

In [129]:
#No need to drop the cause column as it is the cause_id which we will need in fire_incident_table
#california_fire.drop('CAUSE', axis=1, inplace=True)
#california_fire.head()

In [130]:
# Check the column names.
california_fire.columns

Index(['AcresBurned', 'ArchiveYear', 'Counties', 'CountyIds', 'Start_Date',
       'End_Date', 'Injuries', 'Latitude', 'Longitude', 'MajorIncident',
       'Location', 'Name', 'PercentContained', 'StructuresDamaged',
       'StructuresDestroyed', 'StructuresEvacuated', 'StructuresThreatened',
       'YEAR_', 'STATE', 'FIRE_NAME', 'CAUSE', 'SHAPE_Length', 'SHAPE_Area',
       'GIS_ACRES', 'Cause_Description'],
      dtype='object')

In [131]:
california_fire.isnull().sum()

AcresBurned                3
ArchiveYear                0
Counties                   0
CountyIds                  0
Start_Date                 0
End_Date                  59
Injuries                1607
Latitude                   0
Longitude                  0
MajorIncident              0
Location                   0
Name                       0
PercentContained           3
StructuresDamaged       1667
StructuresDestroyed     1552
StructuresEvacuated     1734
StructuresThreatened    1704
YEAR_                   1331
STATE                   1331
FIRE_NAME               1333
CAUSE                      0
SHAPE_Length            1331
SHAPE_Area              1331
GIS_ACRES               1331
Cause_Description          0
dtype: int64

In [132]:
# Drop fire
california_fire.drop(columns=['FIRE_NAME','GIS_ACRES', 'StructuresEvacuated', 'YEAR_', 'SHAPE_Length', 'SHAPE_Area'], axis=1, inplace=True)
california_fire

,AcresBurned,ArchiveYear,Counties,CountyIds,Start_Date,End_Date,Injuries,Latitude,Longitude,MajorIncident,Location,Name,PercentContained,StructuresDamaged,StructuresDestroyed,StructuresThreatened,STATE,CAUSE,Cause_Description
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,NaN,37.857000,-120.086000,False,3 miles east of Groveland along Hwy 120,Rim Fire,100.0,NaN,NaN,NaN,NaN,14,Unidentified
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,NaN,34.585595,-118.423176,False,Angeles National Forest,Powerhouse Fire,100.0,NaN,NaN,NaN,NaN,14,Unidentified
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,NaN,33.709500,-116.728850,False,Hwy 243 & Hwy 74 near Mountain Center,Mountain Fire,100.0,NaN,NaN,NaN,CA,9,Miscellaneous
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,NaN,39.120000,-120.650000,False,"Deadwood Ridge, northeast of Foresthill",American Fire,100.0,NaN,NaN,NaN,NaN,14,Unidentified
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.000000,0.000000,True,Southbound Highway 101 at Camarillo Springs Ro...,Springs Fire,100.0,6.0,10.0,NaN,NaN,14,Unidentified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,9.0,2019,Riverside,33,2019-10-10,2019-10-10,NaN,33.827979,-117.499619,False,"Eagle Canyon Rd. and Cajalco Rd., southwest of...",Eagle Fire,100.0,NaN,NaN,NaN,CA,10,Vehicle
1730,2.0,2019,Nevada,29,2019-06-28,2019-06-28,NaN,39.409722,-121.000556,False,"Off of Long Point Road and Old Mill Road, Sou...",Long Fire,100.0,NaN,NaN,NaN,CA,8,Playing with fire
1731,NaN,2019,Yolo,57,2019-11-25,NaT,NaN,38.734634,-121.729691,False,"County Road 102 and County Road 17, North of W...",Cashe Fire,NaN,NaN,NaN,NaN,NaN,14,Unidentified
1732,NaN,2019,San Diego,37,2019-10-22,NaT,NaN,33.351145,-117.403719,False,"Near Basilone Road and Las Pulgas Road, near C...",Oak Fire,NaN,NaN,NaN,NaN,NaN,14,Unidentified
1733,NaN,2019,Riverside,33,2019-10-14,NaT,NaN,33.451480,-116.058980,False,Johnson Street and Ave 82,Johnson Fire,NaN,NaN,NaN,NaN,NaN,14,Unidentified

In [133]:
# Rename columns.
california_fire = california_fire.rename(columns={'Name':'Fire_Name',
                                                  'AcresBurned':'Total_Acres_Burned',
                                                  'ArchiveYear':'Archive_Year',
                                                  'Start_Date':'Fire_Started_Date',
                                                  'End_Date':'Fire_Extinguished_Date',
                                                  'PercentContained':'Percent_Contained',
                                                  'Counties':'County_Name',
                                                  'CountyIds':'County_ID',
                                                  'MajorIncident':'Major_Incident',
                                                  'StructuresDestroyed':'Structures_Destroyed',
                                                  'StructuresDamaged':'Structures_Damaged',
                                                  'StructuresEvacuated':'Structures_Evacuated',
                                                  'StructuresThreatened':'Structures_Threatened',
                                                  'STATE':'State',
                                                  })
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,Location,Fire_Name,Percent_Contained,Structures_Damaged,Structures_Destroyed,Structures_Threatened,State,CAUSE,Cause_Description
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,NaN,37.857000,-120.086000,False,3 miles east of Groveland along Hwy 120,Rim Fire,100.0,NaN,NaN,NaN,NaN,14,Unidentified
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,NaN,34.585595,-118.423176,False,Angeles National Forest,Powerhouse Fire,100.0,NaN,NaN,NaN,NaN,14,Unidentified
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,NaN,33.709500,-116.728850,False,Hwy 243 & Hwy 74 near Mountain Center,Mountain Fire,100.0,NaN,NaN,NaN,CA,9,Miscellaneous
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,NaN,39.120000,-120.650000,False,"Deadwood Ridge, northeast of Foresthill",American Fire,100.0,NaN,NaN,NaN,NaN,14,Unidentified
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.000000,0.000000,True,Southbound Highway 101 at Camarillo Springs Ro...,Springs Fire,100.0,6.0,10.0,NaN,NaN,14,Unidentified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1729,9.0,2019,Riverside,33,2019-10-10,2019-10-10,NaN,33.827979,-117.499619,False,"Eagle Canyon Rd. and Cajalco Rd., southwest of...",Eagle Fire,100.0,NaN,NaN,NaN,CA,10,Vehicle
1730,2.0,2019,Nevada,29,2019-06-28,2019-06-28,NaN,39.409722,-121.000556,False,"Off of Long Point Road and Old Mill Road, Sou...",Long Fire,100.0,NaN,NaN,NaN,CA,8,Playing with fire
1731,NaN,2019,Yolo,57,2019-11-25,NaT,NaN,38.734634,-121.729691,False,"County Road 102 and County Road 17, North of W...",Cashe Fire,NaN,NaN,NaN,NaN,NaN,14,Unidentified
1732,NaN,2019,San Diego,37,2019-10-22,NaT,NaN,33.351145,-117.403719,False,"Near Basilone Road and Las Pulgas Road, near C...",Oak Fire,NaN,NaN,NaN,NaN,NaN,14,Unidentified
1733,NaN,2019,Riverside,33,2019-10-14,NaT,NaN,33.451480,-116.058980,False,Johnson Street and Ave 82,Johnson Fire,NaN,NaN,NaN,NaN,NaN,14,Unidentified

In [134]:
california_fire.isnull().sum()

Total_Acres_Burned           3
Archive_Year                 0
County_Name                  0
County_ID                    0
Fire_Started_Date            0
Fire_Extinguished_Date      59
Injuries                  1607
Latitude                     0
Longitude                    0
Major_Incident               0
Location                     0
Fire_Name                    0
Percent_Contained            3
Structures_Damaged        1667
Structures_Destroyed      1552
Structures_Threatened     1704
State                     1331
CAUSE                        0
Cause_Description            0
dtype: int64

In [135]:
california_fire["Structures_Damaged"] = california_fire["Structures_Damaged"].fillna(0)
california_fire["Structures_Destroyed"] = california_fire["Structures_Destroyed"].fillna(0)
california_fire["Structures_Threatened"] = california_fire["Structures_Threatened"].fillna(0)
california_fire["Injuries"] = california_fire["Injuries"].fillna(0)

In [136]:
california_fire.isnull().sum()

Total_Acres_Burned           3
Archive_Year                 0
County_Name                  0
County_ID                    0
Fire_Started_Date            0
Fire_Extinguished_Date      59
Injuries                     0
Latitude                     0
Longitude                    0
Major_Incident               0
Location                     0
Fire_Name                    0
Percent_Contained            3
Structures_Damaged           0
Structures_Destroyed         0
Structures_Threatened        0
State                     1331
CAUSE                        0
Cause_Description            0
dtype: int64

In [137]:
#california_fire = pd.concat(columns=['Structures_Damaged', 'Structures_Threatened', 'Structures_Destroyed'])
california_fire["Structure_Impacted"]= california_fire["Structures_Damaged"] + california_fire["Structures_Destroyed"]+ california_fire["Structures_Threatened"]

In [138]:
california_fire["Structure_Impacted"].isnull().sum()

0

In [139]:
california_fire.drop_duplicates(subset=['Fire_Name', 'Fire_Started_Date', 'Fire_Extinguished_Date','County_Name'], inplace =True)

In [140]:
california_fire.drop_duplicates('Fire_Name', inplace=True)

In [141]:
california_fire.duplicated().sum()

0

In [142]:
california_fire.drop(columns=['Structures_Damaged', 'Structures_Destroyed', 'Structures_Threatened'], axis=1, inplace=True)

In [143]:
california_fire.isnull().sum()

Total_Acres_Burned          2
Archive_Year                0
County_Name                 0
County_ID                   0
Fire_Started_Date           0
Fire_Extinguished_Date     43
Injuries                    0
Latitude                    0
Longitude                   0
Major_Incident              0
Location                    0
Fire_Name                   0
Percent_Contained           2
State                     953
CAUSE                       0
Cause_Description           0
Structure_Impacted          0
dtype: int64

In [145]:
california_fire["State"] = california_fire["State"].fillna('CA')
california_fire.isnull().sum()

Total_Acres_Burned         2
Archive_Year               0
County_Name                0
County_ID                  0
Fire_Started_Date          0
Fire_Extinguished_Date    43
Injuries                   0
Latitude                   0
Longitude                  0
Major_Incident             0
Location                   0
Fire_Name                  0
Percent_Contained          2
State                      0
CAUSE                      0
Cause_Description          0
Structure_Impacted         0
dtype: int64

In [146]:
#Already did this step after merging the two tables and replaced NaNs with 14
#california_fire["Cause_Description"] = california_fire["Cause_Description"].fillna('Unidentified')
#california_fire.isnull().sum()

In [147]:
california_fire.dropna(subset=['Percent_Contained', 'Fire_Extinguished_Date'], inplace=True)
california_fire.isnull().sum()

Total_Acres_Burned        0
Archive_Year              0
County_Name               0
County_ID                 0
Fire_Started_Date         0
Fire_Extinguished_Date    0
Injuries                  0
Latitude                  0
Longitude                 0
Major_Incident            0
Location                  0
Fire_Name                 0
Percent_Contained         0
State                     0
CAUSE                     0
Cause_Description         0
Structure_Impacted        0
dtype: int64

In [148]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,Location,Fire_Name,Percent_Contained,State,CAUSE,Cause_Description,Structure_Impacted
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,3 miles east of Groveland along Hwy 120,Rim Fire,100.0,CA,14,Unidentified,0.0
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,Angeles National Forest,Powerhouse Fire,100.0,CA,14,Unidentified,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,Hwy 243 & Hwy 74 near Mountain Center,Mountain Fire,100.0,CA,9,Miscellaneous,0.0
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,0.0,39.120000,-120.650000,False,"Deadwood Ridge, northeast of Foresthill",American Fire,100.0,CA,14,Unidentified,0.0
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.000000,0.000000,True,Southbound Highway 101 at Camarillo Springs Ro...,Springs Fire,100.0,CA,14,Unidentified,16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1720,10.0,2019,San Diego,37,2019-10-15,2019-10-16,0.0,32.762706,-117.097441,False,"Off Fairmont Avenue and Aldine Drive, Northwes...",Fairmont Fire,100.0,CA,14,Unidentified,0.0
1721,10.0,2019,Tehama,52,2019-10-09,2019-10-08,0.0,39.847708,-122.160416,False,"Inghram Road, South Corning",Inghram Fire,100.0,CA,14,Unidentified,1.0
1722,10.0,2019,Amador,3,2019-09-25,2019-09-25,1.0,38.332083,-120.671310,True,"Electra Road and Highway 49, east of Jackson",Electra Fire,100.0,CA,14,Unidentified,0.0
1726,10.0,2019,Siskiyou,47,2019-06-16,2019-06-21,0.0,41.946220,-122.401570,False,"Deer Run Road, east of Iron Gate Reservoir",IronGate Fire,100.0,CA,14,Unidentified,0.0
1727,10.0,2019,Butte,4,2019-04-30,2019-05-08,0.0,39.839580,-121.957000,False,"Off Hamilton Nord Cana Hwy & Cana Hwy, northea...",Cana Fire,100.0,CA,14,Unidentified,0.0

In [149]:
#get data for county whose latlong is 0
missing_latlng_df = california_fire[(california_fire['Latitude'] == 0) & (california_fire['Longitude'] == 0)]
missing_latlng_df

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,Location,Fire_Name,Percent_Contained,State,CAUSE,Cause_Description,Structure_Impacted
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,0.0,0.0,True,Southbound Highway 101 at Camarillo Springs Ro...,Springs Fire,100.0,CA,14,Unidentified,16.0
28,917.0,2013,Monterey,27,2013-12-16,2013-12-20,0.0,0.0,0.0,False,Pfeiffer Ridge Road and Highway 1 near Big Sur,Pfeiffer Fire,100.0,CA,9,Miscellaneous,0.0
47,311.0,2013,Riverside,33,2013-02-28,2013-03-02,0.0,0.0,0.0,False,"Rio Rancho Rd & Calle Hermosa, Jurupa Valley",Jurupa Fire,100.0,CA,14,Unidentified,0.0
53,296.0,2013,Lake,17,2013-01-22,2013-01-23,0.0,0.0,0.0,False,"North of Highway 29, southeast of Kelseyville",Becks Fire,100.0,CA,14,Unidentified,0.0
62,226.0,2013,Glenn,11,2013-06-12,2013-06-17,0.0,0.0,0.0,False,15 miles northwest of Elk Creek off County Roa...,Daves Fire,100.0,CA,14,Unidentified,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,4500.0,2018,Solano,48,2018-10-07,2019-01-04,0.0,0.0,0.0,False,"Branscombe Road south of Hwy 12, Suisun City",Branscombe Fire,100.0,CA,14,Unidentified,0.0
1217,293.0,2018,Kern,15,2018-05-16,2019-01-04,0.0,0.0,0.0,False,"Twisselman Road and Kecks Road, west of Highwa...",Twisselman Fire,100.0,CA,14,Unidentified,0.0
1358,33.0,2018,Tulare,54,2018-02-18,2019-01-03,0.0,0.0,0.0,False,"Road 136 and Avenue 440, Community of Orosi",Wilcox Fire,100.0,CA,14,Unidentified,0.0
1442,0.0,2018,Santa Barbara,"42,56",2018-01-09,2019-01-03,0.0,0.0,0.0,True,"Montecito, Summerland and Carpenteria",Montecito Flooding / Mudflows,100.0,CA,14,Unidentified,0.0
1672,30.0,2019,Riverside,33,2019-04-09,2019-04-10,0.0,0.0,0.0,False,"Hwy 111 and Tramway Rd, Palm Springs",Girasol Fire,100.0,CA,14,Unidentified,0.0

In [150]:
#read county lat long csv
path ="Resources/calCounties.csv"

county_latlong_df = pd.read_csv(path)
county_latlong_df.head()

,county,county_ascii,county_full,county_fips,state_id,state_name,lat,lng,population
0,Los Angeles,Los Angeles,Los Angeles County,6037,CA,California,34.3207,-118.2248,10081570
1,San Diego,San Diego,San Diego County,6073,CA,California,33.0341,-116.7353,3316073
2,Orange,Orange,Orange County,6059,CA,California,33.7030,-117.7611,3168044
3,Riverside,Riverside,Riverside County,6065,CA,California,33.7437,-115.9938,2411439
4,San Bernardino,San Bernardino,San Bernardino County,6071,CA,California,34.8414,-116.1784,2149031

In [151]:
# renaming the columns
county_latlong_df= county_latlong_df.rename(columns={'county':'County_Name','lat':'Latitude','lng':'Longitude'})

county_latlong_df.head()

,County_Name,county_ascii,county_full,county_fips,state_id,state_name,Latitude,Longitude,population
0,Los Angeles,Los Angeles,Los Angeles County,6037,CA,California,34.3207,-118.2248,10081570
1,San Diego,San Diego,San Diego County,6073,CA,California,33.0341,-116.7353,3316073
2,Orange,Orange,Orange County,6059,CA,California,33.7030,-117.7611,3168044
3,Riverside,Riverside,Riverside County,6065,CA,California,33.7437,-115.9938,2411439
4,San Bernardino,San Bernardino,San Bernardino County,6071,CA,California,34.8414,-116.1784,2149031

In [152]:
#keep only required columns needed to merge with missing latlng
county_latlong_df_sub=county_latlong_df[["County_Name","Latitude","Longitude"]]
county_latlong_df_sub

        County_Name  Latitude  Longitude
0       Los Angeles   34.3207  -118.2248
1         San Diego   33.0341  -116.7353
2            Orange   33.7030  -117.7611
3         Riverside   33.7437  -115.9938
4    San Bernardino   34.8414  -116.1784
5       Santa Clara   37.2318  -121.6951
6           Alameda   37.6469  -121.8889
7        Sacramento   38.4493  -121.3443
8      Contra Costa   37.9191  -121.9278
9            Fresno   36.7582  -119.6493
10             Kern   35.3429  -118.7299
11    San Francisco   37.7562  -122.4430
12          Ventura   34.4565  -119.0836
13        San Mateo   37.4229  -122.3290
14      San Joaquin   37.9348  -121.2714
15       Stanislaus   37.5591  -120.9977
16           Sonoma   38.5283  -122.8874
17           Tulare   36.2201  -118.8005
18    Santa Barbara   34.6729  -120.0165
19           Solano   38.2700  -121.9329
20         Monterey   36.2172  -121.2392
21           Placer   39.0635  -120.7175
22  San Luis Obispo   35.3871  -120.4045
23       Santa Cruz   37.0562  -122.0018
24           Merced   37.1919  -120.7177
25            Marin   38.0734  -122.7234
26            Butte   39.6669  -121.6007
27             Yolo   38.6866  -121.9016
28        El Dorado   38.7787  -120.5247
29         Imperial   33.0395  -115.3654
30           Shasta   40.7637  -122.0405
31           Madera   37.2180  -119.7627
32            Kings   36.0753  -119.8155
33             Napa   38.5065  -122.3305
34         Humboldt   40.6993  -123.8756
35           Nevada   39.3014  -120.7685
36           Sutter   39.0346  -121.6948
37        Mendocino   39.4402  -123.3915
38             Yuba   39.2690  -121.3513
39             Lake   39.0996  -122.7532
40           Tehama   40.1256  -122.2341
41       San Benito   36.6057  -121.0750
42         Tuolumne   38.0276  -119.9548
43        Calaveras   38.2046  -120.5541
44         Siskiyou   41.5927  -122.5404
45           Amador   38.4464  -120.6511
46           Lassen   40.6736  -120.5943
47            Glenn   39.5982  -122.3920
48        Del Norte   41.7431  -123.8972
49           Colusa   39.1775  -122.2370
50           Plumas   40.0046  -120.8385
51             Inyo   36.5111  -117.4107
52         Mariposa   37.5815  -119.9054
53             Mono   37.9391  -118.8868
54          Trinity   40.6507  -123.1126
55            Modoc   41.5898  -120.7250
56           Sierra   39.5803  -120.5160
57           Alpine   38.5972  -119.8207

In [153]:
#dropping lat lng column for which lat and lng is missing from missing_latlng_df 
missing_latlng_df.drop(["Longitude","Latitude"], axis = 1, inplace=True)

SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [154]:
missing_latlng_df

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Major_Incident,Location,Fire_Name,Percent_Contained,State,CAUSE,Cause_Description,Structure_Impacted
4,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,True,Southbound Highway 101 at Camarillo Springs Ro...,Springs Fire,100.0,CA,14,Unidentified,16.0
28,917.0,2013,Monterey,27,2013-12-16,2013-12-20,0.0,False,Pfeiffer Ridge Road and Highway 1 near Big Sur,Pfeiffer Fire,100.0,CA,9,Miscellaneous,0.0
47,311.0,2013,Riverside,33,2013-02-28,2013-03-02,0.0,False,"Rio Rancho Rd & Calle Hermosa, Jurupa Valley",Jurupa Fire,100.0,CA,14,Unidentified,0.0
53,296.0,2013,Lake,17,2013-01-22,2013-01-23,0.0,False,"North of Highway 29, southeast of Kelseyville",Becks Fire,100.0,CA,14,Unidentified,0.0
62,226.0,2013,Glenn,11,2013-06-12,2013-06-17,0.0,False,15 miles northwest of Elk Creek off County Roa...,Daves Fire,100.0,CA,14,Unidentified,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,4500.0,2018,Solano,48,2018-10-07,2019-01-04,0.0,False,"Branscombe Road south of Hwy 12, Suisun City",Branscombe Fire,100.0,CA,14,Unidentified,0.0
1217,293.0,2018,Kern,15,2018-05-16,2019-01-04,0.0,False,"Twisselman Road and Kecks Road, west of Highwa...",Twisselman Fire,100.0,CA,14,Unidentified,0.0
1358,33.0,2018,Tulare,54,2018-02-18,2019-01-03,0.0,False,"Road 136 and Avenue 440, Community of Orosi",Wilcox Fire,100.0,CA,14,Unidentified,0.0
1442,0.0,2018,Santa Barbara,"42,56",2018-01-09,2019-01-03,0.0,True,"Montecito, Summerland and Carpenteria",Montecito Flooding / Mudflows,100.0,CA,14,Unidentified,0.0
1672,30.0,2019,Riverside,33,2019-04-09,2019-04-10,0.0,False,"Hwy 111 and Tramway Rd, Palm Springs",Girasol Fire,100.0,CA,14,Unidentified,0.0

In [155]:
#merging the missing lat_lng_df witg the lat_lng_df to get missing values
lat_lng_df = missing_latlng_df.merge(county_latlong_df_sub, how='left', on ="County_Name")
lat_lng_df

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Major_Incident,Location,Fire_Name,Percent_Contained,State,CAUSE,Cause_Description,Structure_Impacted,Latitude,Longitude
0,24251.0,2013,Ventura,56,2013-05-02,2013-05-11,10.0,True,Southbound Highway 101 at Camarillo Springs Ro...,Springs Fire,100.0,CA,14,Unidentified,16.0,34.4565,-119.0836
1,917.0,2013,Monterey,27,2013-12-16,2013-12-20,0.0,False,Pfeiffer Ridge Road and Highway 1 near Big Sur,Pfeiffer Fire,100.0,CA,9,Miscellaneous,0.0,36.2172,-121.2392
2,311.0,2013,Riverside,33,2013-02-28,2013-03-02,0.0,False,"Rio Rancho Rd & Calle Hermosa, Jurupa Valley",Jurupa Fire,100.0,CA,14,Unidentified,0.0,33.7437,-115.9938
3,296.0,2013,Lake,17,2013-01-22,2013-01-23,0.0,False,"North of Highway 29, southeast of Kelseyville",Becks Fire,100.0,CA,14,Unidentified,0.0,39.0996,-122.7532
4,226.0,2013,Glenn,11,2013-06-12,2013-06-17,0.0,False,15 miles northwest of Elk Creek off County Roa...,Daves Fire,100.0,CA,14,Unidentified,0.0,39.5982,-122.3920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,4500.0,2018,Solano,48,2018-10-07,2019-01-04,0.0,False,"Branscombe Road south of Hwy 12, Suisun City",Branscombe Fire,100.0,CA,14,Unidentified,0.0,38.2700,-121.9329
128,293.0,2018,Kern,15,2018-05-16,2019-01-04,0.0,False,"Twisselman Road and Kecks Road, west of Highwa...",Twisselman Fire,100.0,CA,14,Unidentified,0.0,35.3429,-118.7299
129,33.0,2018,Tulare,54,2018-02-18,2019-01-03,0.0,False,"Road 136 and Avenue 440, Community of Orosi",Wilcox Fire,100.0,CA,14,Unidentified,0.0,36.2201,-118.8005
130,0.0,2018,Santa Barbara,"42,56",2018-01-09,2019-01-03,0.0,True,"Montecito, Summerland and Carpenteria",Montecito Flooding / Mudflows,100.0,CA,14,Unidentified,0.0,34.6729,-120.0165
131,30.0,2019,Riverside,33,2019-04-09,2019-04-10,0.0,False,"Hwy 111 and Tramway Rd, Palm Springs",Girasol Fire,100.0,CA,14,Unidentified,0.0,33.7437,-115.9938

In [156]:
california_fire.drop(california_fire[(california_fire["Latitude"] == 0) & (california_fire['Longitude'] == 0)].index,inplace=True)

In [157]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,Location,Fire_Name,Percent_Contained,State,CAUSE,Cause_Description,Structure_Impacted
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,3 miles east of Groveland along Hwy 120,Rim Fire,100.0,CA,14,Unidentified,0.0
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,Angeles National Forest,Powerhouse Fire,100.0,CA,14,Unidentified,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,Hwy 243 & Hwy 74 near Mountain Center,Mountain Fire,100.0,CA,9,Miscellaneous,0.0
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,0.0,39.120000,-120.650000,False,"Deadwood Ridge, northeast of Foresthill",American Fire,100.0,CA,14,Unidentified,0.0
5,22992.0,2013,Fresno,10,2013-07-22,2013-09-24,0.0,37.279000,-119.318000,False,Seven miles north of Big Creek,Aspen Fire,100.0,CA,14,Unidentified,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1720,10.0,2019,San Diego,37,2019-10-15,2019-10-16,0.0,32.762706,-117.097441,False,"Off Fairmont Avenue and Aldine Drive, Northwes...",Fairmont Fire,100.0,CA,14,Unidentified,0.0
1721,10.0,2019,Tehama,52,2019-10-09,2019-10-08,0.0,39.847708,-122.160416,False,"Inghram Road, South Corning",Inghram Fire,100.0,CA,14,Unidentified,1.0
1722,10.0,2019,Amador,3,2019-09-25,2019-09-25,1.0,38.332083,-120.671310,True,"Electra Road and Highway 49, east of Jackson",Electra Fire,100.0,CA,14,Unidentified,0.0
1726,10.0,2019,Siskiyou,47,2019-06-16,2019-06-21,0.0,41.946220,-122.401570,False,"Deer Run Road, east of Iron Gate Reservoir",IronGate Fire,100.0,CA,14,Unidentified,0.0
1727,10.0,2019,Butte,4,2019-04-30,2019-05-08,0.0,39.839580,-121.957000,False,"Off Hamilton Nord Cana Hwy & Cana Hwy, northea...",Cana Fire,100.0,CA,14,Unidentified,0.0

In [158]:
#Appending the lat_lnf_df with the main df
california_fire = california_fire.append(lat_lng_df)

In [189]:
#reset index after appending
california_fire = california_fire.reset_index(drop=True)

In [190]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,...,CA,14,Unidentified,0.0,17.0,36.0,25.8,6.0,NaN,NaN
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,...,CA,14,Unidentified,0.0,16.7,32.2,24.0,36.9,1009.2,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,...,CA,9,Miscellaneous,0.0,28.3,43.3,36.3,14.0,1004.7,0.0
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,0.0,39.120000,-120.650000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,22992.0,2013,Fresno,10,2013-07-22,2013-09-24,0.0,37.279000,-119.318000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,4500.0,2018,Solano,48,2018-10-07,2019-01-04,0.0,38.270000,-121.932900,False,...,CA,14,Unidentified,0.0,18.3,27.5,22.4,29.8,1011.5,0.0
1146,293.0,2018,Kern,15,2018-05-16,2019-01-04,0.0,35.342900,-118.729900,False,...,CA,14,Unidentified,0.0,15.0,26.1,20.2,14.4,1015.7,0.0
1147,33.0,2018,Tulare,54,2018-02-18,2019-01-03,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,3.9,21.1,12.3,14.3,1014.6,NaN
1148,0.0,2018,Santa Barbara,"42,56",2018-01-09,2019-01-03,0.0,34.672900,-120.016500,True,...,CA,14,Unidentified,0.0,11.1,17.2,14.0,16.9,NaN,59.4
1149,30.0,2019,Riverside,33,2019-04-09,2019-04-10,0.0,33.743700,-115.993800,False,...,CA,14,Unidentified,0.0,20.0,36.7,26.9,20.3,1009.0,0.0

In [191]:
fire_facts = california_fire[["Fire_Name", "Archive_Year", "Fire_Started_Date", "Fire_Extinguished_Date", "Cause_Description"]]
fire_facts.columns = map(str.lower, fire_facts.columns)

In [192]:
fire_impacts = california_fire[["Fire_Name", "Total_Acres_Burned","County_ID", "Injuries", "Structure_Impacted"]]
fire_impacts.columns = map(str.lower, fire_impacts.columns)

In [193]:
fire_cause = fire_cause.rename(columns={'CAUSE':'cause_id'})
fire_cause.columns = map(str.lower, fire_cause.columns)
# Renaming the cause column to cause_id which we will use in fire_incidents table
california_fire = california_fire.rename(columns={'CAUSE':'Cause_id'})

In [194]:
fire_incidents = california_fire[["Fire_Name", "Fire_Started_Date", "Fire_Extinguished_Date", "Archive_Year", "County_ID", "State","Cause_id","Cause_Description", "Percent_Contained", "Total_Acres_Burned", "Major_Incident"]]
fire_incidents.columns = map(str.lower, fire_incidents.columns)
fire_incidents.columns

Index(['fire_name', 'fire_started_date', 'fire_extinguished_date',
       'archive_year', 'county_id', 'state', 'cause_id', 'cause_description',
       'percent_contained', 'total_acres_burned', 'major_incident'],
      dtype='object')

In [195]:
# Extract weather data.

tmax = []
tmin = []
tavg = []
wspd = []
pres = []
prcp = []


for index, row in california_fire[["Latitude", "Longitude", "Fire_Started_Date"]].iterrows():
    
    # Set time period.
    start = datetime.combine(row["Fire_Started_Date"], time.min)

    # Create Point for Counties.
    location = Point(row["Latitude"], row["Longitude"])
    
    
    # Get weather data for the dates.
    data = Daily(location, start, start).fetch()
    if len(data.tmax) > 0:
        #print("The mean maximum air temperature in °C:")
        #print(data.tmax[0])
        tmax.append(data.tmax[0]) 
    else:
        tmax.append(0)
    
    if len(data.tmin) > 0:
        #print("The mean minimum air temperature in °C:")
        #print(data.tmin[0])
        tmin.append(data.tmin[0]) 
    else:
        tmin.append(0)
        
    if len(data.tavg) > 0:
        #print("The mean air temperature in °C:")
        #print(data.tavg[0])
        tavg.append(data.tavg[0])
    else:
        tavg.append(0)
        
    if len(data.wspd) > 0:
        #print("The mean wind speed in km/hr:")
        #print(data.wspd[0])
        wspd.append(data.wspd[0])    
    else:
        wspd.append(1)
        
    if len(data.pres) > 0:
        #print("The mean wind speed in km/hr:")
        #print(data.wspd[0])
        pres.append(data.pres[0])    
    else:
        pres.append(1)

    if len(data.prcp) > 0:
        #print("The mean wind speed in km/hr:")
        #print(data.wspd[0])
        prcp.append(data.prcp[0])    
    else:
        prcp.append(0)

Warning: Cannot load daily/full/KAPV0.csv.gz from https://bulk.meteostat.net/v2/
Warning: Cannot load daily/full/69542.csv.gz from https://bulk.meteostat.net/v2/

In [196]:
california_fire["Minimum_Temp"] = tmin
california_fire["Maximum_Temp"] = tmax
california_fire["Average_Temp"] = tavg
california_fire["Wind_Speed"] = wspd
california_fire["Air_Pressure"] = pres
california_fire["Precipitation"] = prcp

In [197]:
#chk 0 weather data
missing_weather_df = california_fire[(california_fire['Minimum_Temp'] == 0) & (california_fire['Maximum_Temp'] == 0) &
                                    (california_fire['Wind_Speed'] == 1) & (california_fire['Air_Pressure'] == 1) &
                                    (california_fire['Precipitation'] == 0) & (california_fire['Average_Temp'] == 0)]
missing_weather_df

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,0.0,39.120000,-120.650000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,22992.0,2013,Fresno,10,2013-07-22,2013-09-24,0.0,37.279000,-119.318000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6,14754.0,2013,Siskiyou,47,2013-07-31,2013-08-31,0.0,41.320000,-123.176000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
7,12503.0,2013,Humboldt,12,2013-08-10,2013-08-12,0.0,41.035000,-123.488000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
11,6965.0,2013,Tehama,52,2013-05-01,2013-05-09,6.0,40.190062,-121.595555,True,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1131,80.0,2016,Madera,20,2016-07-21,2016-07-25,0.0,37.218000,-119.762700,True,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1134,42.0,2016,Lassen,18,2016-07-30,2016-08-01,0.0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1137,25.0,2016,Lake,17,2016-07-29,2016-07-31,0.0,39.099600,-122.753200,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1140,16031.0,2017,Tulare,54,2017-06-24,2018-01-09,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1142,21.0,2017,Shasta,45,2017-06-13,2018-01-09,0.0,40.763700,-122.040500,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [198]:
get_weather_df = missing_weather_df.copy()
get_weather_df

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
3,27440.0,2013,Placer,31,2013-08-10,2013-08-30,0.0,39.120000,-120.650000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,22992.0,2013,Fresno,10,2013-07-22,2013-09-24,0.0,37.279000,-119.318000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
6,14754.0,2013,Siskiyou,47,2013-07-31,2013-08-31,0.0,41.320000,-123.176000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
7,12503.0,2013,Humboldt,12,2013-08-10,2013-08-12,0.0,41.035000,-123.488000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
11,6965.0,2013,Tehama,52,2013-05-01,2013-05-09,6.0,40.190062,-121.595555,True,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1131,80.0,2016,Madera,20,2016-07-21,2016-07-25,0.0,37.218000,-119.762700,True,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1134,42.0,2016,Lassen,18,2016-07-30,2016-08-01,0.0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1137,25.0,2016,Lake,17,2016-07-29,2016-07-31,0.0,39.099600,-122.753200,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1140,16031.0,2017,Tulare,54,2017-06-24,2018-01-09,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1142,21.0,2017,Shasta,45,2017-06-13,2018-01-09,0.0,40.763700,-122.040500,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [61]:
from config import api_key
import requests

weather_data = []

url = "https://api.worldweatheronline.com/premium/v1/past-weather.ashx?"

count = 1
for index,row in get_weather_df.iterrows():
    lat = row["Latitude"] 
    lng = row["Longitude"] 
    param = f"{lat},{lng}"
    fire_date = str(row["Fire_Started_Date"])

    county_url = url + "q=" + param + "&date=" + fire_date  + "&format=json&key=" + api_key 
    print(str(count) + ". " + county_url)
   
    
    try:
        count += 1

        county_weather = requests.get(county_url).json()

        date = county_weather["data"]["weather"][0]["date"]
        max_temp = county_weather["data"]["weather"][0]["maxtempC"]
        min_temp = county_weather["data"]["weather"][0]["mintempC"]
        avg_temp = county_weather["data"]["weather"][0]["avgtempC"]
        wind_speed = county_weather["data"]["weather"][0]["hourly"][0]["windspeedKmph"]
        air_pressure = county_weather["data"]["weather"][0]["hourly"][0]["pressure"]
        precipitaion = county_weather["data"]["weather"][0]["hourly"][0]["precipMM"]
    
        
        weather_data.append({"date": date,
                             "fire-date": fire_date,
                             "Lat":lat,
                             "Lng":lng,
                          "max temp": max_temp,
                          "min temp": min_temp,
                          "avg temp": avg_temp,
                          "wind speed": wind_speed,
                          "air pressure": air_pressure,
                          "precipitaion": precipitaion})
        
    except Exception as e:
        print(e)
        print("Weather not found")
        weather_data.append({"date": "1970-01-01",
                             "fire-date": fire_date,
                             "Lat":lat,
                             "Lng":lng,
                          "max temp": 0,
                          "min temp": 0,
                          "avg temp": 0,
                          "wind speed": 1,
                          "air pressure": 1,
                          "precipitaion": 0})

1. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.12,-120.65&date=2013-08-10&format=json&key=360703db5d9a413dbb663922212109
2. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.279,-119.318&date=2013-07-22&format=json&key=360703db5d9a413dbb663922212109
3. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.32,-123.176&date=2013-07-31&format=json&key=360703db5d9a413dbb663922212109
4. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.035,-123.488&date=2013-08-10&format=json&key=360703db5d9a413dbb663922212109
5. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.190062,-121.595555&date=2013-05-01&format=json&key=360703db5d9a413dbb663922212109
6. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.288877,-116.941311&date=2013-05-01&format=json&key=360703db5d9a413dbb663922212109
7. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.12111,-116.52579&date=2013-05-23&format=json&key=360703db5d9a413dbb663922212109
8. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.208,-118.444&date=2013-08-24&format=json&key=360703db5d9a413dbb663922212109
9. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.58202,-119.91071&date=2013-06-16&format=json&key=360703db5d9a413dbb663922212109
10. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.04458,-116.5209&date=2013-05-26&format=json&key=360703db5d9a413dbb663922212109
11. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.25108,-120.02778&date=2013-08-05&format=json&key=360703db5d9a413dbb663922212109
12. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.707,-118.588&date=2013-08-18&format=json&key=360703db5d9a413dbb663922212109
13. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.774,-120.298&date=2013-07-08&format=json&key=360703db5d9a413dbb663922212109
14. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.071556,-117.048397&date=2013-06-28&format=json&key=360703db5d9a413dbb663922212109
15. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.00842,-120.764666&date=2013-08-18&format=json&key=360703db5d9a413dbb663922212109
16. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.2415,-121.035&date=2013-07-03&format=json&key=360703db5d9a413dbb663922212109
17. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.15832,-120.05131&date=2013-06-01&format=json&key=360703db5d9a413dbb663922212109
18. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.302,-117.598&date=2013-08-20&format=json&key=360703db5d9a413dbb663922212109
19. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.602575,-118.01651&date=2013-02-24&format=json&key=360703db5d9a413dbb663922212109
20. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.628,-122.289&date=2013-10-03&format=json&key=360703db5d9a413dbb663922212109
21. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.160346,-120.937494&date=2013-05-03&format=json&key=360703db5d9a413dbb663922212109
22. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.116295,-119.635004&date=2013-04-30&format=json&key=360703db5d9a413dbb663922212109
23. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.149,-117.908&date=2013-09-23&format=json&key=360703db5d9a413dbb663922212109
24. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.35,-117.62&date=2013-08-08&format=json&key=360703db5d9a413dbb663922212109
25. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.775057,-121.737213&date=2013-06-08&format=json&key=360703db5d9a413dbb663922212109
26. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.514139,-122.560862&date=2013-05-01&format=json&key=360703db5d9a413dbb663922212109
27. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.5445,-121.3754&date=2013-08-19&format=json&key=360703db5d9a413dbb663922212109
28. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.7218,-119.2248&date=2013-06-25&format=json&key=360703db5d9a413dbb663922212109
29. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.258,-118.459&date=2013-09-08&format=json&key=360703db5d9a413dbb663922212109
30. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.03776,-121.006939&date=2013-06-04&format=json&key=360703db5d9a413dbb663922212109
31. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.882214,-122.567525&date=2013-11-08&format=json&key=360703db5d9a413dbb663922212109
32. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.287,-117.451&date=2013-08-17&format=json&key=360703db5d9a413dbb663922212109
33. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.1531,-120.8973&date=2013-06-29&format=json&key=360703db5d9a413dbb663922212109
34. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.88886,-120.958126&date=2013-08-09&format=json&key=360703db5d9a413dbb663922212109
35. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.27783,-120.966016&date=2013-06-12&format=json&key=360703db5d9a413dbb663922212109
36. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.1927,-119.7917&date=2013-05-19&format=json&key=360703db5d9a413dbb663922212109
37. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.316,-117.352&date=2013-07-25&format=json&key=360703db5d9a413dbb663922212109
38. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.169379,-119.75636&date=2013-06-12&format=json&key=360703db5d9a413dbb663922212109
39. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.013682,-122.491894&date=2013-08-16&format=json&key=360703db5d9a413dbb663922212109
40. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.838,-116.61&date=2013-08-06&format=json&key=360703db5d9a413dbb663922212109
41. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0448,-122.7656&date=2013-11-23&format=json&key=360703db5d9a413dbb663922212109
42. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.373,-122.7338&date=2013-07-09&format=json&key=360703db5d9a413dbb663922212109
43. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.1591,-122.5906&date=2013-08-07&format=json&key=360703db5d9a413dbb663922212109
44. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.965364,-120.696362&date=2013-07-22&format=json&key=360703db5d9a413dbb663922212109
45. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.9777,-122.683&date=2013-09-15&format=json&key=360703db5d9a413dbb663922212109
46. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.288877,-116.941311&date=2013-04-20&format=json&key=360703db5d9a413dbb663922212109
47. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.98058,-122.81796&date=2013-06-20&format=json&key=360703db5d9a413dbb663922212109
48. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.96201,-116.907213&date=2013-05-20&format=json&key=360703db5d9a413dbb663922212109
49. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.9289,-122.5818&date=2013-11-23&format=json&key=360703db5d9a413dbb663922212109
50. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.333,-123.376&date=2013-08-03&format=json&key=360703db5d9a413dbb663922212109
51. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.99647,-116.84137&date=2013-06-09&format=json&key=360703db5d9a413dbb663922212109
52. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.901,-121.368&date=2014-07-30&format=json&key=360703db5d9a413dbb663922212109
53. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.72,-121.562&date=2014-07-31&format=json&key=360703db5d9a413dbb663922212109
54. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.1336,-121.2144&date=2014-07-30&format=json&key=360703db5d9a413dbb663922212109
55. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.4314,-122.750788&date=2014-07-11&format=json&key=360703db5d9a413dbb663922212109

56. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.141,-122.805&date=2014-07-30&format=json&key=360703db5d9a413dbb663922212109
57. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.664,-122.454&date=2014-07-01&format=json&key=360703db5d9a413dbb663922212109
58. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.7206,-118.4747&date=2014-08-18&format=json&key=360703db5d9a413dbb663922212109
59. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.1703,-117.8816&date=2014-01-16&format=json&key=360703db5d9a413dbb663922212109
60. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.642,-118.15&date=2014-07-11&format=json&key=360703db5d9a413dbb663922212109
61. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.89,-120.79&date=2014-07-01&format=json&key=360703db5d9a413dbb663922212109
62. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.134597,-121.790183&date=2014-01-02&format=json&key=360703db5d9a413dbb663922212109
63. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.3433,-119.6581&date=2014-08-18&format=json&key=360703db5d9a413dbb663922212109
64. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.42384,-122.37432&date=2014-09-15&format=json&key=360703db5d9a413dbb663922212109
65. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.311915,-119.604124&date=2014-09-14&format=json&key=360703db5d9a413dbb663922212109
66. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.0,40.34&date=2014-10-07&format=json&key=360703db5d9a413dbb663922212109
67. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.267,-117.867&date=2014-08-17&format=json&key=360703db5d9a413dbb663922212109
68. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.235,-117.771&date=2014-08-14&format=json&key=360703db5d9a413dbb663922212109
69. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.7103,-120.197&date=2014-06-10&format=json&key=360703db5d9a413dbb663922212109
70. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=120.679019,38.178241&date=2014-06-20&format=json&key=360703db5d9a413dbb663922212109
'weather'
Weather not found
71. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.058,-120.66&date=2014-06-22&format=json&key=360703db5d9a413dbb663922212109
72. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.5719,-121.3415&date=2014-07-05&format=json&key=360703db5d9a413dbb663922212109
73. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.103,-121.117&date=2014-04-30&format=json&key=360703db5d9a413dbb663922212109
74. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=121.999,38.453&date=2014-06-12&format=json&key=360703db5d9a413dbb663922212109
'weather'
Weather not found
75. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.8218,-121.0226&date=2014-07-07&format=json&key=360703db5d9a413dbb663922212109
76. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.695961,-122.384054&date=2014-09-11&format=json&key=360703db5d9a413dbb663922212109
77. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.742747,-119.241493&date=2014-06-11&format=json&key=360703db5d9a413dbb663922212109
78. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.41,-123.24&date=2014-07-01&format=json&key=360703db5d9a413dbb663922212109
79. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.0,18.4&date=2014-08-26&format=json&key=360703db5d9a413dbb663922212109
80. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.796,-123.374&date=2014-08-11&format=json&key=360703db5d9a413dbb663922212109
81. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.874,-118.905&date=2015-07-31&format=json&key=360703db5d9a413dbb663922212109
82. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.8863538,-122.4762475&date=2015-07-29&format=json&key=360703db5d9a413dbb663922212109
83. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.8142503,-122.4867319&date=2015-08-09&format=json&key=360703db5d9a413dbb663922212109
84. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.938,-120.105&date=2015-08-03&format=json&key=360703db5d9a413dbb663922212109
85. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.24,-118.54&date=2015-07-19&format=json&key=360703db5d9a413dbb663922212109
86. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.279722,-119.50014&date=2015-07-25&format=json&key=360703db5d9a413dbb663922212109
87. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.399,-121.392&date=2015-07-30&format=json&key=360703db5d9a413dbb663922212109
88. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.339,-117.478&date=2015-07-17&format=json&key=360703db5d9a413dbb663922212109
89. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.3845,-121.3732&date=2015-08-19&format=json&key=360703db5d9a413dbb663922212109
90. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.165767,-119.523943&date=2015-06-18&format=json&key=360703db5d9a413dbb663922212109
91. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=55.23,-122.0&date=2015-09-02&format=json&key=360703db5d9a413dbb663922212109
92. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.08312,-121.06963&date=2015-05-11&format=json&key=360703db5d9a413dbb663922212109
93. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.925764,-122.879272&date=2015-08-22&format=json&key=360703db5d9a413dbb663922212109
94. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.367,-117.683&date=2015-07-17&format=json&key=360703db5d9a413dbb663922212109
95. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.485,-121.851&date=2015-02-24&format=json&key=360703db5d9a413dbb663922212109
96. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.383889,-116.868611&date=2015-07-24&format=json&key=360703db5d9a413dbb663922212109
97. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.295667,-123.784067&date=2015-07-24&format=json&key=360703db5d9a413dbb663922212109
98. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.1058823,-124.0720419&date=2015-08-18&format=json&key=360703db5d9a413dbb663922212109
99. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.050833333333,-120.70166666667&date=2015-04-13&format=json&key=360703db5d9a413dbb663922212109
100. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.29226,-121.172117&date=2015-07-23&format=json&key=360703db5d9a413dbb663922212109
101. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.052,-120.5577&date=2015-08-13&format=json&key=360703db5d9a413dbb663922212109
102. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.3506868,-121.7786799&date=2015-08-08&format=json&key=360703db5d9a413dbb663922212109
103. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.49845,-118.9009&date=2015-07-30&format=json&key=360703db5d9a413dbb663922212109
104. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.856422,-121.101623&date=2015-07-23&format=json&key=360703db5d9a413dbb663922212109
105. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.67868,-121.93244&date=2015-08-02&format=json&key=360703db5d9a413dbb663922212109
106. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.77937,-120.19482&date=2015-06-15&format=json&key=360703db5d9a413dbb663922212109
107. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.875667,-121.033667&date=2015-06-19&format=json&key=360703db5d9a413dbb663922212109
108. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.0783472,-117.0487863&date=2015-07-12&format=json&key=360703db5d9a413dbb663922212109
109. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.43301,-123.36316&date=2015-07-30&format=json&key=360703db5d9a413dbb663922212109

110. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.400196,-120.553075&date=2015-09-09&format=json&key=360703db5d9a413dbb663922212109
111. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.24523,-121.20324&date=2015-07-28&format=json&key=360703db5d9a413dbb663922212109
112. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.5287,-122.3415&date=2015-06-16&format=json&key=360703db5d9a413dbb663922212109
113. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.7806004,-123.248214&date=2015-06-28&format=json&key=360703db5d9a413dbb663922212109
114. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.12362,-121.194256&date=2015-08-29&format=json&key=360703db5d9a413dbb663922212109
115. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.831478,-122.53428&date=2015-08-24&format=json&key=360703db5d9a413dbb663922212109
116. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.1093,-123.774&date=2015-07-28&format=json&key=360703db5d9a413dbb663922212109
117. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.6115,-118.45628&date=2016-06-23&format=json&key=360703db5d9a413dbb663922212109
118. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.30372,-117.49342&date=2016-08-16&format=json&key=360703db5d9a413dbb663922212109
119. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.851,-123.118&date=2016-08-27&format=json&key=360703db5d9a413dbb663922212109
120. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.28771,-117.27338&date=2016-08-07&format=json&key=360703db5d9a413dbb663922212109
121. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.776,-119.643&date=2016-06-15&format=json&key=360703db5d9a413dbb663922212109
122. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.09974,-120.51057&date=2016-08-09&format=json&key=360703db5d9a413dbb663922212109
123. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.89741,-122.60664&date=2016-08-13&format=json&key=360703db5d9a413dbb663922212109
124. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.38123,-121.20059&date=2016-05-22&format=json&key=360703db5d9a413dbb663922212109
125. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.0749,-120.452041&date=2016-07-01&format=json&key=360703db5d9a413dbb663922212109
126. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.623,-123.557&date=2016-06-07&format=json&key=360703db5d9a413dbb663922212109
127. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.3915,-120.7845&date=2016-09-11&format=json&key=360703db5d9a413dbb663922212109
128. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.01542,-121.25029&date=2016-06-04&format=json&key=360703db5d9a413dbb663922212109
129. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.701,-119.144&date=2016-06-30&format=json&key=360703db5d9a413dbb663922212109
130. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.94536,-119.25959&date=2016-10-11&format=json&key=360703db5d9a413dbb663922212109
131. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.97,-119.14&date=2016-06-25&format=json&key=360703db5d9a413dbb663922212109
132. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.28486,-123.82268&date=2016-08-22&format=json&key=360703db5d9a413dbb663922212109
133. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.2013,-118.7212&date=2016-08-26&format=json&key=360703db5d9a413dbb663922212109
134. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.16965,-121.38775&date=2016-08-18&format=json&key=360703db5d9a413dbb663922212109
135. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.4976,-118.5097&date=2016-08-28&format=json&key=360703db5d9a413dbb663922212109
136. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.92,-121.32&date=2016-09-26&format=json&key=360703db5d9a413dbb663922212109
137. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.68313,-118.21793&date=2016-07-13&format=json&key=360703db5d9a413dbb663922212109
138. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.12366,-122.50373&date=2016-06-26&format=json&key=360703db5d9a413dbb663922212109
139. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.26874,-120.90265&date=2016-06-17&format=json&key=360703db5d9a413dbb663922212109
140. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.75972,-120.029626&date=2016-09-13&format=json&key=360703db5d9a413dbb663922212109
141. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.14161,-120.62048&date=2016-07-04&format=json&key=360703db5d9a413dbb663922212109
142. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.17072,-121.42238&date=2016-06-07&format=json&key=360703db5d9a413dbb663922212109
143. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.25601,-119.65776&date=2016-07-04&format=json&key=360703db5d9a413dbb663922212109
144. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.24504,-118.60344&date=2016-08-04&format=json&key=360703db5d9a413dbb663922212109
145. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=5487.0,-120.841536&date=2016-07-09&format=json&key=360703db5d9a413dbb663922212109
'weather'
Weather not found
146. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.3228,-119.7738&date=2016-08-04&format=json&key=360703db5d9a413dbb663922212109
147. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.8866,-122.04726&date=2016-07-15&format=json&key=360703db5d9a413dbb663922212109
148. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.2833,-121.3306&date=2016-06-18&format=json&key=360703db5d9a413dbb663922212109
149. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0863,-122.7891&date=2016-07-19&format=json&key=360703db5d9a413dbb663922212109
150. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.77135,-120.251&date=2016-06-11&format=json&key=360703db5d9a413dbb663922212109
151. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.1934,-120.9293&date=2016-06-23&format=json&key=360703db5d9a413dbb663922212109
152. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.7299,-123.5044&date=2016-09-10&format=json&key=360703db5d9a413dbb663922212109
153. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.3183,-117.3189&date=2016-09-07&format=json&key=360703db5d9a413dbb663922212109
154. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.79549,-121.00299&date=2016-07-22&format=json&key=360703db5d9a413dbb663922212109
155. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.09974,-120.51057&date=2016-08-09&format=json&key=360703db5d9a413dbb663922212109
156. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.8748511,-123.4267011&date=2016-08-30&format=json&key=360703db5d9a413dbb663922212109
157. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.68403,-122.26015&date=2016-08-09&format=json&key=360703db5d9a413dbb663922212109
158. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.3131,-121.06452&date=2016-06-03&format=json&key=360703db5d9a413dbb663922212109
159. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.58972,-118.15589&date=2016-07-01&format=json&key=360703db5d9a413dbb663922212109
160. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.2171,-121.08036&date=2016-04-24&format=json&key=360703db5d9a413dbb663922212109
161. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.8378273,-121.0381507&date=2016-05-12&format=json&key=360703db5d9a413dbb663922212109
162. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.217,-118.551&date=2016-10-20&format=json&key=360703db5d9a413dbb663922212109
163. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.57554,-120.00606&date=2016-08-18&format=json&key=360703db5d9a413dbb663922212109

164. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.07045,-120.14013&date=2017-07-11&format=json&key=360703db5d9a413dbb663922212109
165. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.61757,-120.21321&date=2017-07-16&format=json&key=360703db5d9a413dbb663922212109
166. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.841,-123.474&date=2017-08-15&format=json&key=360703db5d9a413dbb663922212109
167. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.93273,-120.20014&date=2017-07-09&format=json&key=360703db5d9a413dbb663922212109
168. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=42.039,-123.218&date=2017-08-14&format=json&key=360703db5d9a413dbb663922212109
169. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.76025,-123.10003&date=2017-08-30&format=json&key=360703db5d9a413dbb663922212109
170. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.27138,-118.48555&date=2017-09-27&format=json&key=360703db5d9a413dbb663922212109
171. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.69573,-119.93499&date=2017-08-30&format=json&key=360703db5d9a413dbb663922212109
172. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.44663,-119.64622&date=2017-08-29&format=json&key=360703db5d9a413dbb663922212109
173. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.12089,-120.37116&date=2017-05-18&format=json&key=360703db5d9a413dbb663922212109
174. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.22957,-118.2674&date=2017-09-01&format=json&key=360703db5d9a413dbb663922212109
175. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.538,-119.598&date=2017-08-14&format=json&key=360703db5d9a413dbb663922212109
176. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.07228,-120.26561&date=2017-04-20&format=json&key=360703db5d9a413dbb663922212109
177. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.17598,-123.36882&date=2017-08-07&format=json&key=360703db5d9a413dbb663922212109
178. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.9034,-120.9761&date=2017-07-29&format=json&key=360703db5d9a413dbb663922212109
179. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.853,-123.676&date=2017-08-07&format=json&key=360703db5d9a413dbb663922212109
180. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.77896,-118.89627&date=2017-07-07&format=json&key=360703db5d9a413dbb663922212109
181. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.75312,-120.75485&date=2017-09-05&format=json&key=360703db5d9a413dbb663922212109
182. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.01387,-122.64543&date=2017-10-08&format=json&key=360703db5d9a413dbb663922212109
183. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.96655,-120.89261&date=2017-05-12&format=json&key=360703db5d9a413dbb663922212109
184. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.269125,-120.620791&date=2017-07-02&format=json&key=360703db5d9a413dbb663922212109
185. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.543,-118.654&date=2017-07-30&format=json&key=360703db5d9a413dbb663922212109
186. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.76,-118.406&date=2017-09-01&format=json&key=360703db5d9a413dbb663922212109
187. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.94373,-119.44751&date=2017-07-18&format=json&key=360703db5d9a413dbb663922212109
188. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.21616,-119.48067&date=2017-09-03&format=json&key=360703db5d9a413dbb663922212109
189. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.98352,-121.81623&date=2017-09-12&format=json&key=360703db5d9a413dbb663922212109
190. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.24549,-121.12792&date=2017-10-09&format=json&key=360703db5d9a413dbb663922212109
191. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.37397,-119.83556&date=2017-09-03&format=json&key=360703db5d9a413dbb663922212109
192. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.3762,-119.9646&date=2017-06-28&format=json&key=360703db5d9a413dbb663922212109
193. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.85763,-121.29581&date=2017-06-28&format=json&key=360703db5d9a413dbb663922212109
194. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.95036,-116.88066&date=2017-08-14&format=json&key=360703db5d9a413dbb663922212109
195. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.11989,-120.74968&date=2017-08-06&format=json&key=360703db5d9a413dbb663922212109
196. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.3975,-122.8428&date=2017-07-05&format=json&key=360703db5d9a413dbb663922212109
197. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.616986,-120.369347&date=2017-06-11&format=json&key=360703db5d9a413dbb663922212109
198. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.72163,-121.30451&date=2017-07-13&format=json&key=360703db5d9a413dbb663922212109
199. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.34292,-121.12004&date=2017-08-30&format=json&key=360703db5d9a413dbb663922212109
200. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.46111,-119.48284&date=2017-11-13&format=json&key=360703db5d9a413dbb663922212109
201. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.45809,-118.87676&date=2017-06-07&format=json&key=360703db5d9a413dbb663922212109
202. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.08492,-117.03826&date=2017-08-03&format=json&key=360703db5d9a413dbb663922212109
203. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.478,-123.506&date=2017-07-19&format=json&key=360703db5d9a413dbb663922212109
204. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.59257,-117.14979&date=2017-12-07&format=json&key=360703db5d9a413dbb663922212109
205. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.34659,-116.66107&date=2017-07-22&format=json&key=360703db5d9a413dbb663922212109
206. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.21177,-119.87525&date=2017-05-15&format=json&key=360703db5d9a413dbb663922212109
207. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.59804,-118.47939&date=2017-06-10&format=json&key=360703db5d9a413dbb663922212109
208. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.44543,-122.85194&date=2017-09-12&format=json&key=360703db5d9a413dbb663922212109
209. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.9465,-119.8036&date=2017-05-20&format=json&key=360703db5d9a413dbb663922212109
210. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.9864,-120.89746&date=2017-08-20&format=json&key=360703db5d9a413dbb663922212109
211. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.704679,-120.405077&date=2017-06-11&format=json&key=360703db5d9a413dbb663922212109
212. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.19008,-118.76152&date=2017-10-12&format=json&key=360703db5d9a413dbb663922212109
213. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.41204,-117.03031&date=2017-07-23&format=json&key=360703db5d9a413dbb663922212109
214. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.80968,-120.48641&date=2017-08-26&format=json&key=360703db5d9a413dbb663922212109
215. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.30104,-117.45646&date=2017-04-30&format=json&key=360703db5d9a413dbb663922212109
216. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.5355,-120.6585&date=2017-04-29&format=json&key=360703db5d9a413dbb663922212109
217. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.62823,-120.30046&date=2017-08-13&format=json&key=360703db5d9a413dbb663922212109

218. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0199,-122.57487&date=2017-10-14&format=json&key=360703db5d9a413dbb663922212109
219. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.15016,-122.576&date=2017-10-06&format=json&key=360703db5d9a413dbb663922212109
220. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=117.337331,34.015742&date=2017-08-31&format=json&key=360703db5d9a413dbb663922212109
'weather'
Weather not found
221. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.11794,-123.76099&date=2017-08-03&format=json&key=360703db5d9a413dbb663922212109
222. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.20152,-117.14466&date=2017-07-22&format=json&key=360703db5d9a413dbb663922212109
223. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.13278,-120.9204&date=2017-09-03&format=json&key=360703db5d9a413dbb663922212109
224. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.89423,-119.00334&date=2017-05-31&format=json&key=360703db5d9a413dbb663922212109
225. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.19325,-121.08406&date=2017-10-09&format=json&key=360703db5d9a413dbb663922212109
226. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.4403,-120.2913&date=2017-08-02&format=json&key=360703db5d9a413dbb663922212109
227. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.60736,-120.5828&date=2017-05-19&format=json&key=360703db5d9a413dbb663922212109
228. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.36914,-120.0088&date=2017-06-15&format=json&key=360703db5d9a413dbb663922212109
229. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.20988,-116.46989&date=2017-08-26&format=json&key=360703db5d9a413dbb663922212109
230. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.94599,-122.81135&date=2017-08-08&format=json&key=360703db5d9a413dbb663922212109
231. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.32063,-122.83208&date=2017-06-18&format=json&key=360703db5d9a413dbb663922212109
232. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.42604,-123.03344&date=2017-09-12&format=json&key=360703db5d9a413dbb663922212109
233. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.64404,-118.99944&date=2017-07-18&format=json&key=360703db5d9a413dbb663922212109
234. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.21556,-118.56578&date=2017-10-26&format=json&key=360703db5d9a413dbb663922212109
235. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.22551,-118.05545&date=2017-10-17&format=json&key=360703db5d9a413dbb663922212109
236. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.70639,-118.47307&date=2017-08-05&format=json&key=360703db5d9a413dbb663922212109
237. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.38109,-121.00391&date=2017-11-25&format=json&key=360703db5d9a413dbb663922212109
238. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.48712,-121.85645&date=2017-04-03&format=json&key=360703db5d9a413dbb663922212109
239. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.81517,-122.28165&date=2017-11-02&format=json&key=360703db5d9a413dbb663922212109
240. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.96275,-121.08753&date=2017-06-29&format=json&key=360703db5d9a413dbb663922212109
241. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.38247,-120.53443&date=2017-06-03&format=json&key=360703db5d9a413dbb663922212109
242. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.05076,-118.90004&date=2017-05-14&format=json&key=360703db5d9a413dbb663922212109
243. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.59302,-118.46734&date=2017-09-29&format=json&key=360703db5d9a413dbb663922212109
244. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.02705,-123.63721&date=2017-08-28&format=json&key=360703db5d9a413dbb663922212109
245. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.29831,-122.70449&date=2017-08-26&format=json&key=360703db5d9a413dbb663922212109
246. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.65963,-120.34802&date=2017-07-07&format=json&key=360703db5d9a413dbb663922212109
247. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.03697,-123.64214&date=2017-08-31&format=json&key=360703db5d9a413dbb663922212109
248. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.60633,-118.4642&date=2017-06-04&format=json&key=360703db5d9a413dbb663922212109
249. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.804,-123.375&date=2017-08-02&format=json&key=360703db5d9a413dbb663922212109
250. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.90092,-120.93371&date=2017-06-16&format=json&key=360703db5d9a413dbb663922212109
251. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.902149,-120.983684&date=2017-06-11&format=json&key=360703db5d9a413dbb663922212109
252. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.099681,-120.443545&date=2017-08-23&format=json&key=360703db5d9a413dbb663922212109
253. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.60001,-118.4683&date=2017-05-12&format=json&key=360703db5d9a413dbb663922212109
254. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.52055,-118.62882&date=2017-08-31&format=json&key=360703db5d9a413dbb663922212109
255. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.27582,-123.64281&date=2017-08-03&format=json&key=360703db5d9a413dbb663922212109
256. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.76343,-121.04445&date=2017-09-23&format=json&key=360703db5d9a413dbb663922212109
257. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.50488,-117.02132&date=2017-10-10&format=json&key=360703db5d9a413dbb663922212109
258. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.68347,-122.2654&date=2017-06-13&format=json&key=360703db5d9a413dbb663922212109
259. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.01748,-122.49327&date=2017-09-05&format=json&key=360703db5d9a413dbb663922212109
260. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.10858,-118.81979&date=2017-07-05&format=json&key=360703db5d9a413dbb663922212109
261. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.983,-119.91508&date=2017-05-18&format=json&key=360703db5d9a413dbb663922212109
262. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.39799,-123.57562&date=2017-08-01&format=json&key=360703db5d9a413dbb663922212109
263. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.61332,-120.7109&date=2017-05-28&format=json&key=360703db5d9a413dbb663922212109
264. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.41231,-119.87465&date=2017-10-03&format=json&key=360703db5d9a413dbb663922212109
265. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.92602,-121.5935&date=2017-08-17&format=json&key=360703db5d9a413dbb663922212109
266. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.2771,-120.94328&date=2017-05-17&format=json&key=360703db5d9a413dbb663922212109
267. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.87983,-122.5415&date=2017-08-10&format=json&key=360703db5d9a413dbb663922212109
268. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.947,-120.87492&date=2017-06-28&format=json&key=360703db5d9a413dbb663922212109
269. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.76888,-120.15846&date=2017-09-20&format=json&key=360703db5d9a413dbb663922212109
270. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.10067,-119.32109&date=2017-09-11&format=json&key=360703db5d9a413dbb663922212109
271. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.34421,-120.72274&date=2017-08-28&format=json&key=360703db5d9a413dbb663922212109

272. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.23925,-117.85182&date=2017-08-03&format=json&key=360703db5d9a413dbb663922212109
273. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.73596,-119.78256&date=2017-09-07&format=json&key=360703db5d9a413dbb663922212109
274. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.702,-123.508&date=2017-07-25&format=json&key=360703db5d9a413dbb663922212109
275. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.841,-123.474&date=2017-06-25&format=json&key=360703db5d9a413dbb663922212109
276. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.6549,-119.88581&date=2018-07-13&format=json&key=360703db5d9a413dbb663922212109
277. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.80583,-122.18183&date=2018-06-30&format=json&key=360703db5d9a413dbb663922212109
278. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.9425,-122.43&date=2018-09-05&format=json&key=360703db5d9a413dbb663922212109
279. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.896,-122.219&date=2018-08-09&format=json&key=360703db5d9a413dbb663922212109
280. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.349,-119.929&date=2018-08-01&format=json&key=360703db5d9a413dbb663922212109
281. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.633536,-120.868091&date=2018-07-27&format=json&key=360703db5d9a413dbb663922212109
282. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0674,-122.59848&date=2018-06-23&format=json&key=360703db5d9a413dbb663922212109
283. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.35068,-121.77867&date=2018-06-23&format=json&key=360703db5d9a413dbb663922212109
284. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.07944,-123.688056&date=2018-08-16&format=json&key=360703db5d9a413dbb663922212109
285. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.97896,-119.98329&date=2018-08-06&format=json&key=360703db5d9a413dbb663922212109
286. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.6734,-118.21881&date=2018-07-08&format=json&key=360703db5d9a413dbb663922212109
287. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.69601,-122.44468&date=2018-09-08&format=json&key=360703db5d9a413dbb663922212109
288. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.64978,-122.58218&date=2018-06-09&format=json&key=360703db5d9a413dbb663922212109
289. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.99344,-121.52225&date=2018-08-09&format=json&key=360703db5d9a413dbb663922212109
290. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.85156,-120.77206&date=2018-05-02&format=json&key=360703db5d9a413dbb663922212109
291. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.616251,-123.52019&date=2018-09-04&format=json&key=360703db5d9a413dbb663922212109
292. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.40755,-120.99322&date=2018-06-04&format=json&key=360703db5d9a413dbb663922212109
293. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.71537,-118.08449&date=2018-04-19&format=json&key=360703db5d9a413dbb663922212109
294. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.11416667,-120.09222222&date=2018-08-19&format=json&key=360703db5d9a413dbb663922212109
295. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.82877,-123.08489&date=2018-07-31&format=json&key=360703db5d9a413dbb663922212109
296. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.42623,-120.95408&date=2018-07-06&format=json&key=360703db5d9a413dbb663922212109
297. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.378333,-120.901167&date=2018-06-04&format=json&key=360703db5d9a413dbb663922212109
298. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.316137,-120.45053&date=2018-06-27&format=json&key=360703db5d9a413dbb663922212109
299. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.95515,-120.86256&date=2018-06-26&format=json&key=360703db5d9a413dbb663922212109
300. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.51777778,-118.6525&date=2018-08-18&format=json&key=360703db5d9a413dbb663922212109
301. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.10181,-119.623981&date=2018-06-04&format=json&key=360703db5d9a413dbb663922212109
302. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.0232,-119.76576&date=2018-03-27&format=json&key=360703db5d9a413dbb663922212109
303. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.085,-123.051&date=2018-07-01&format=json&key=360703db5d9a413dbb663922212109
304. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.18401,-120.69955&date=2018-10-13&format=json&key=360703db5d9a413dbb663922212109
305. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.36888889,-122.89055556&date=2018-08-19&format=json&key=360703db5d9a413dbb663922212109
306. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.46543,-122.65582&date=2018-06-01&format=json&key=360703db5d9a413dbb663922212109
307. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.59036,-120.82355&date=2018-07-12&format=json&key=360703db5d9a413dbb663922212109
308. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.02017,-122.57496&date=2018-08-26&format=json&key=360703db5d9a413dbb663922212109
309. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.9352,-121.11936&date=2018-06-09&format=json&key=360703db5d9a413dbb663922212109
310. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.1234,-118.72905&date=2018-06-29&format=json&key=360703db5d9a413dbb663922212109
311. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.94666,-121.27049&date=2018-07-15&format=json&key=360703db5d9a413dbb663922212109
312. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.83116,-120.19336&date=2018-11-08&format=json&key=360703db5d9a413dbb663922212109
313. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.179167,-119.431667&date=2018-08-27&format=json&key=360703db5d9a413dbb663922212109
314. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.056944,-121.01638&date=2018-05-20&format=json&key=360703db5d9a413dbb663922212109
315. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.06715,-122.59789&date=2018-07-09&format=json&key=360703db5d9a413dbb663922212109
316. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.696879,-119.304499&date=2018-06-27&format=json&key=360703db5d9a413dbb663922212109
317. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.2976,-122.512012&date=2018-07-04&format=json&key=360703db5d9a413dbb663922212109
318. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.08529,-121.09354&date=2018-06-24&format=json&key=360703db5d9a413dbb663922212109
319. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.56349,-116.732032&date=2018-07-04&format=json&key=360703db5d9a413dbb663922212109
320. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.32744,-121.10903&date=2018-05-29&format=json&key=360703db5d9a413dbb663922212109
321. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.95234,-121.21597&date=2018-07-15&format=json&key=360703db5d9a413dbb663922212109
322. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.47677,-119.84299&date=2018-06-15&format=json&key=360703db5d9a413dbb663922212109
323. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.824,-121.90215&date=2018-07-24&format=json&key=360703db5d9a413dbb663922212109
324. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.91152,-122.86854&date=2018-07-21&format=json&key=360703db5d9a413dbb663922212109
325. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.96689,-121.28185&date=2018-02-07&format=json&key=360703db5d9a413dbb663922212109

326. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.62194,-123.28774&date=2018-11-08&format=json&key=360703db5d9a413dbb663922212109
327. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.17156,-118.51651&date=2018-08-17&format=json&key=360703db5d9a413dbb663922212109
328. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.42638,-118.70443&date=2018-07-19&format=json&key=360703db5d9a413dbb663922212109
329. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.08583,-121.05722&date=2018-07-15&format=json&key=360703db5d9a413dbb663922212109
330. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.92436,-119.94083&date=2018-04-12&format=json&key=360703db5d9a413dbb663922212109
331. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.91842,-122.85276&date=2018-09-03&format=json&key=360703db5d9a413dbb663922212109
332. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.69965,-120.0545&date=2018-08-04&format=json&key=360703db5d9a413dbb663922212109
333. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.34453,-123.85404&date=2018-07-15&format=json&key=360703db5d9a413dbb663922212109
334. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.467999,-117.003829&date=2018-05-04&format=json&key=360703db5d9a413dbb663922212109
335. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.99309,-120.02137&date=2018-07-14&format=json&key=360703db5d9a413dbb663922212109
336. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.10499,-120.55324&date=2018-06-02&format=json&key=360703db5d9a413dbb663922212109
337. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.22791,-119.50461&date=2018-07-10&format=json&key=360703db5d9a413dbb663922212109
338. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.64805,-122.98442&date=2018-06-04&format=json&key=360703db5d9a413dbb663922212109
339. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.19817,-119.80414&date=2018-07-09&format=json&key=360703db5d9a413dbb663922212109
340. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.319291,-120.460189&date=2019-10-18&format=json&key=360703db5d9a413dbb663922212109
341. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.420988,-121.371276&date=2019-07-18&format=json&key=360703db5d9a413dbb663922212109
342. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.538467,-120.965105&date=2019-09-29&format=json&key=360703db5d9a413dbb663922212109
343. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.79591,-121.260305&date=2019-07-28&format=json&key=360703db5d9a413dbb663922212109
344. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.034,-118.345&date=2019-09-06&format=json&key=360703db5d9a413dbb663922212109
345. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.593,-120.581&date=2019-08-28&format=json&key=360703db5d9a413dbb663922212109
346. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.528469,-117.273157&date=2019-09-04&format=json&key=360703db5d9a413dbb663922212109
347. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.343761,-119.913717&date=2019-06-05&format=json&key=360703db5d9a413dbb663922212109
348. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.943799,-120.275298&date=2019-08-08&format=json&key=360703db5d9a413dbb663922212109
349. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.30759,-119.96498&date=2019-05-29&format=json&key=360703db5d9a413dbb663922212109
350. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.22431,-123.12887&date=2019-10-27&format=json&key=360703db5d9a413dbb663922212109
351. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.71011,-119.3547&date=2019-09-01&format=json&key=360703db5d9a413dbb663922212109
352. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.679318,-120.392768&date=2019-07-05&format=json&key=360703db5d9a413dbb663922212109
353. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=44.734,-120.606&date=2019-09-06&format=json&key=360703db5d9a413dbb663922212109
354. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.18479,-118.99229&date=2019-06-02&format=json&key=360703db5d9a413dbb663922212109
355. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.062304,-123.222196&date=2019-09-05&format=json&key=360703db5d9a413dbb663922212109
356. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.4929742,-123.2129356&date=2019-09-07&format=json&key=360703db5d9a413dbb663922212109
357. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.911,-116.980528&date=2019-06-29&format=json&key=360703db5d9a413dbb663922212109
358. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.99136,-121.64118&date=2019-10-27&format=json&key=360703db5d9a413dbb663922212109
359. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.072739,-120.158273&date=2019-07-14&format=json&key=360703db5d9a413dbb663922212109
360. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.95191,-120.8092&date=2019-07-09&format=json&key=360703db5d9a413dbb663922212109
361. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.03855,-119.19454&date=2019-05-03&format=json&key=360703db5d9a413dbb663922212109
362. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.909,-120.306&date=2019-07-17&format=json&key=360703db5d9a413dbb663922212109
363. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.57376,-120.11738&date=2019-06-10&format=json&key=360703db5d9a413dbb663922212109
364. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.906482,-120.992914&date=2019-09-01&format=json&key=360703db5d9a413dbb663922212109
365. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.166674,-122.361112&date=2019-10-24&format=json&key=360703db5d9a413dbb663922212109
366. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.622058,-121.114095&date=2019-08-02&format=json&key=360703db5d9a413dbb663922212109
367. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.69078,-114.57265&date=2019-05-30&format=json&key=360703db5d9a413dbb663922212109
368. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=35.97059,-120.88241&date=2019-06-12&format=json&key=360703db5d9a413dbb663922212109
369. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.4506,-116.857817&date=2019-08-22&format=json&key=360703db5d9a413dbb663922212109
370. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.910498,-122.642572&date=2019-09-04&format=json&key=360703db5d9a413dbb663922212109
371. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.469,-121.3697&date=2019-07-05&format=json&key=360703db5d9a413dbb663922212109
372. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.909792,-117.004667&date=2019-08-12&format=json&key=360703db5d9a413dbb663922212109
373. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=38.99174,-122.7751&date=2019-08-08&format=json&key=360703db5d9a413dbb663922212109
374. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.69055556,-116.953889&date=2019-07-11&format=json&key=360703db5d9a413dbb663922212109
375. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.703546,-117.033598&date=2019-09-30&format=json&key=360703db5d9a413dbb663922212109
376. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.429506,-121.336465&date=2019-10-03&format=json&key=360703db5d9a413dbb663922212109
377. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.512917,-122.740333&date=2019-09-07&format=json&key=360703db5d9a413dbb663922212109
378. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.353667,-117.343833&date=2019-09-02&format=json&key=360703db5d9a413dbb663922212109
379. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.32889,-121.23431&date=2019-06-29&format=json&key=360703db5d9a413dbb663922212109

380. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.2172,-121.2392&date=2013-12-16&format=json&key=360703db5d9a413dbb663922212109
381. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0996,-122.7532&date=2013-01-22&format=json&key=360703db5d9a413dbb663922212109
382. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.5982,-122.392&date=2013-06-12&format=json&key=360703db5d9a413dbb663922212109
383. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.2172,-121.2392&date=2013-07-17&format=json&key=360703db5d9a413dbb663922212109
384. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.3207,-118.2248&date=2013-08-09&format=json&key=360703db5d9a413dbb663922212109
385. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=41.5927,-122.5404&date=2013-07-31&format=json&key=360703db5d9a413dbb663922212109
386. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.7637,-122.0405&date=2013-08-04&format=json&key=360703db5d9a413dbb663922212109
387. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.4402,-123.3915&date=2013-12-30&format=json&key=360703db5d9a413dbb663922212109
388. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.218,-119.7627&date=2013-05-12&format=json&key=360703db5d9a413dbb663922212109
389. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.218,-119.7627&date=2014-07-28&format=json&key=360703db5d9a413dbb663922212109
390. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.4402,-123.3915&date=2014-07-30&format=json&key=360703db5d9a413dbb663922212109
391. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.2172,-121.2392&date=2014-06-19&format=json&key=360703db5d9a413dbb663922212109
392. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2014-08-16&format=json&key=360703db5d9a413dbb663922212109
393. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2014-07-26&format=json&key=360703db5d9a413dbb663922212109
394. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2014-07-17&format=json&key=360703db5d9a413dbb663922212109
395. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2014-05-26&format=json&key=360703db5d9a413dbb663922212109
396. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.4402,-123.3915&date=2014-09-13&format=json&key=360703db5d9a413dbb663922212109
397. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2014-09-05&format=json&key=360703db5d9a413dbb663922212109
398. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0996,-122.7532&date=2014-09-03&format=json&key=360703db5d9a413dbb663922212109
399. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2014-09-07&format=json&key=360703db5d9a413dbb663922212109
400. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.5111,-117.4107&date=2014-09-16&format=json&key=360703db5d9a413dbb663922212109
401. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.4402,-123.3915&date=2014-09-21&format=json&key=360703db5d9a413dbb663922212109
402. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=33.0341,-116.7353&date=2014-05-14&format=json&key=360703db5d9a413dbb663922212109
403. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.5111,-117.4107&date=2015-02-06&format=json&key=360703db5d9a413dbb663922212109
404. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.9391,-118.8868&date=2015-08-14&format=json&key=360703db5d9a413dbb663922212109
405. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.9391,-118.8868&date=2015-02-06&format=json&key=360703db5d9a413dbb663922212109
406. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.218,-119.7627&date=2015-06-18&format=json&key=360703db5d9a413dbb663922212109
407. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2015-09-07&format=json&key=360703db5d9a413dbb663922212109
408. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.3207,-118.2248&date=2015-08-16&format=json&key=360703db5d9a413dbb663922212109
409. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.3207,-118.2248&date=2015-08-16&format=json&key=360703db5d9a413dbb663922212109
410. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.4402,-123.3915&date=2015-07-30&format=json&key=360703db5d9a413dbb663922212109
411. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.6736,-120.5943&date=2015-06-30&format=json&key=360703db5d9a413dbb663922212109
412. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.8414,-116.1784&date=2015-08-01&format=json&key=360703db5d9a413dbb663922212109
413. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2015-06-18&format=json&key=360703db5d9a413dbb663922212109
414. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.5815,-119.9054&date=2015-06-07&format=json&key=360703db5d9a413dbb663922212109
415. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0996,-122.7532&date=2015-06-05&format=json&key=360703db5d9a413dbb663922212109
416. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=34.3207,-118.2248&date=2016-06-20&format=json&key=360703db5d9a413dbb663922212109
417. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.9391,-118.8868&date=2016-08-04&format=json&key=360703db5d9a413dbb663922212109
418. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.6057,-121.075&date=2016-06-17&format=json&key=360703db5d9a413dbb663922212109
419. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.9391,-118.8868&date=2016-08-05&format=json&key=360703db5d9a413dbb663922212109
420. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=37.218,-119.7627&date=2016-07-21&format=json&key=360703db5d9a413dbb663922212109
421. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.6736,-120.5943&date=2016-07-30&format=json&key=360703db5d9a413dbb663922212109
422. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=39.0996,-122.7532&date=2016-07-29&format=json&key=360703db5d9a413dbb663922212109
423. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=36.2201,-118.8005&date=2017-06-24&format=json&key=360703db5d9a413dbb663922212109
424. https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q=40.7637,-122.0405&date=2017-06-13&format=json&key=360703db5d9a413dbb663922212109

In [62]:
weather_df = pd.DataFrame(weather_data)
weather_df

,date,fire-date,Lat,Lng,max temp,min temp,avg temp,wind speed,air pressure,precipitaion
0,2013-08-10,2013-08-10,39.120000,-120.650000,26,6,20,4,1015,0.0
1,2013-07-22,2013-07-22,37.279000,-119.318000,25,15,21,2,1012,0.0
2,2013-07-31,2013-07-31,41.320000,-123.176000,24,1,18,3,1020,0.0
3,2013-08-10,2013-08-10,41.035000,-123.488000,21,4,17,3,1015,0.3
4,2013-05-01,2013-05-01,40.190062,-121.595555,16,1,12,19,1022,0.0
...,...,...,...,...,...,...,...,...,...,...
419,2016-07-21,2016-07-21,37.218000,-119.762700,30,14,26,4,1014,0.0
420,2016-07-30,2016-07-30,40.673600,-120.594300,32,15,28,6,1010,0.0
421,2016-07-29,2016-07-29,39.099600,-122.753200,40,20,34,4,1010,0.0
422,2017-06-24,2017-06-24,36.220100,-118.800500,41,21,35,4,1013,0.0
423,2017-06-13,2017-06-13,40.763700,-122.040500,26,5,21,5,1021,0.0

In [204]:
#read api_weather_data csv
path ="Resources/api_weather_data.csv"

api_weather_data_df = pd.read_csv(path)
api_weather_data_df

,Unnamed: 0,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,3,27440,2013,Placer,31,8/10/2013,8/30/2013,0,39.120000,-120.650000,...,CA,14,Unidentified,0,6,26,20,4,1015,0.0
1,5,22992,2013,Fresno,10,7/22/2013,9/24/2013,0,37.279000,-119.318000,...,CA,14,Unidentified,0,15,25,21,2,1012,0.0
2,7,14754,2013,Siskiyou,47,7/31/2013,8/31/2013,0,41.320000,-123.176000,...,CA,14,Unidentified,0,1,24,18,3,1020,0.0
3,8,12503,2013,Humboldt,12,8/10/2013,8/12/2013,0,41.035000,-123.488000,...,CA,14,Unidentified,0,4,21,17,3,1015,0.3
4,12,6965,2013,Tehama,52,5/1/2013,5/9/2013,6,40.190062,-121.595555,...,CA,14,Unidentified,0,1,16,12,19,1022,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,113,80,2016,Madera,20,7/21/2016,7/25/2016,0,37.218000,-119.762700,...,CA,14,Unidentified,0,14,30,26,4,1014,0.0
420,116,42,2016,Lassen,18,7/30/2016,8/1/2016,0,40.673600,-120.594300,...,CA,2,Equipment Use,0,15,32,28,6,1010,0.0
421,119,25,2016,Lake,17,7/29/2016,7/31/2016,0,39.099600,-122.753200,...,CA,14,Unidentified,0,20,40,34,4,1010,0.0
422,122,16031,2017,Tulare,54,6/24/2017,1/9/2018,0,36.220100,-118.800500,...,CA,14,Unidentified,0,21,41,35,4,1013,0.0
423,124,21,2017,Shasta,45,6/13/2017,1/9/2018,0,40.763700,-122.040500,...,CA,14,Unidentified,0,5,26,21,5,1021,0.0

In [205]:
api_weather_data_df.drop('Unnamed: 0',axis=1, inplace=True)

api_weather_data_df

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,27440,2013,Placer,31,8/10/2013,8/30/2013,0,39.120000,-120.650000,False,...,CA,14,Unidentified,0,6,26,20,4,1015,0.0
1,22992,2013,Fresno,10,7/22/2013,9/24/2013,0,37.279000,-119.318000,False,...,CA,14,Unidentified,0,15,25,21,2,1012,0.0
2,14754,2013,Siskiyou,47,7/31/2013,8/31/2013,0,41.320000,-123.176000,False,...,CA,14,Unidentified,0,1,24,18,3,1020,0.0
3,12503,2013,Humboldt,12,8/10/2013,8/12/2013,0,41.035000,-123.488000,False,...,CA,14,Unidentified,0,4,21,17,3,1015,0.3
4,6965,2013,Tehama,52,5/1/2013,5/9/2013,6,40.190062,-121.595555,True,...,CA,14,Unidentified,0,1,16,12,19,1022,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,80,2016,Madera,20,7/21/2016,7/25/2016,0,37.218000,-119.762700,True,...,CA,14,Unidentified,0,14,30,26,4,1014,0.0
420,42,2016,Lassen,18,7/30/2016,8/1/2016,0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0,15,32,28,6,1010,0.0
421,25,2016,Lake,17,7/29/2016,7/31/2016,0,39.099600,-122.753200,False,...,CA,14,Unidentified,0,20,40,34,4,1010,0.0
422,16031,2017,Tulare,54,6/24/2017,1/9/2018,0,36.220100,-118.800500,False,...,CA,14,Unidentified,0,21,41,35,4,1013,0.0
423,21,2017,Shasta,45,6/13/2017,1/9/2018,0,40.763700,-122.040500,False,...,CA,14,Unidentified,0,5,26,21,5,1021,0.0

In [206]:
api_weather_data_df.dtypes

Total_Acres_Burned          int64
Archive_Year                int64
County_Name                object
County_ID                  object
Fire_Started_Date          object
Fire_Extinguished_Date     object
Injuries                    int64
Latitude                  float64
Longitude                 float64
Major_Incident               bool
Location                   object
Fire_Name                  object
Percent_Contained           int64
State                      object
Cause_id                    int64
Cause_Description          object
Structure_Impacted          int64
Minimum_Temp                int64
Maximum_Temp                int64
Average_Temp                int64
Wind_Speed                  int64
Air_Pressure                int64
Precipitation             float64
dtype: object

In [207]:
for x in missing_weather_df.columns:
    api_weather_data_df[x]=api_weather_data_df[x].astype(missing_weather_df[x].dtypes.name)
api_weather_data_df.dtypes

Total_Acres_Burned        float64
Archive_Year                int64
County_Name                object
County_ID                  object
Fire_Started_Date          object
Fire_Extinguished_Date     object
Injuries                  float64
Latitude                  float64
Longitude                 float64
Major_Incident               bool
Location                   object
Fire_Name                  object
Percent_Contained         float64
State                      object
Cause_id                    int32
Cause_Description          object
Structure_Impacted        float64
Minimum_Temp              float64
Maximum_Temp              float64
Average_Temp              float64
Wind_Speed                float64
Air_Pressure              float64
Precipitation             float64
dtype: object

In [208]:
api_weather_data_df

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,27440.0,2013,Placer,31,8/10/2013,8/30/2013,0.0,39.120000,-120.650000,False,...,CA,14,Unidentified,0.0,6.0,26.0,20.0,4.0,1015.0,0.0
1,22992.0,2013,Fresno,10,7/22/2013,9/24/2013,0.0,37.279000,-119.318000,False,...,CA,14,Unidentified,0.0,15.0,25.0,21.0,2.0,1012.0,0.0
2,14754.0,2013,Siskiyou,47,7/31/2013,8/31/2013,0.0,41.320000,-123.176000,False,...,CA,14,Unidentified,0.0,1.0,24.0,18.0,3.0,1020.0,0.0
3,12503.0,2013,Humboldt,12,8/10/2013,8/12/2013,0.0,41.035000,-123.488000,False,...,CA,14,Unidentified,0.0,4.0,21.0,17.0,3.0,1015.0,0.3
4,6965.0,2013,Tehama,52,5/1/2013,5/9/2013,6.0,40.190062,-121.595555,True,...,CA,14,Unidentified,0.0,1.0,16.0,12.0,19.0,1022.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,80.0,2016,Madera,20,7/21/2016,7/25/2016,0.0,37.218000,-119.762700,True,...,CA,14,Unidentified,0.0,14.0,30.0,26.0,4.0,1014.0,0.0
420,42.0,2016,Lassen,18,7/30/2016,8/1/2016,0.0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0.0,15.0,32.0,28.0,6.0,1010.0,0.0
421,25.0,2016,Lake,17,7/29/2016,7/31/2016,0.0,39.099600,-122.753200,False,...,CA,14,Unidentified,0.0,20.0,40.0,34.0,4.0,1010.0,0.0
422,16031.0,2017,Tulare,54,6/24/2017,1/9/2018,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,21.0,41.0,35.0,4.0,1013.0,0.0
423,21.0,2017,Shasta,45,6/13/2017,1/9/2018,0.0,40.763700,-122.040500,False,...,CA,14,Unidentified,0.0,5.0,26.0,21.0,5.0,1021.0,0.0

In [209]:
california_fire.drop(california_fire[(california_fire['Minimum_Temp'] == 0) & (california_fire['Maximum_Temp'] == 0) &
                                    (california_fire['Wind_Speed'] == 1) & (california_fire['Air_Pressure'] == 1) &
                                    (california_fire['Precipitation'] == 0) & (california_fire['Average_Temp'] == 0)].index,inplace=True)

In [210]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,...,CA,14,Unidentified,0.0,17.0,36.0,25.8,6.0,NaN,NaN
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,...,CA,14,Unidentified,0.0,16.7,32.2,24.0,36.9,1009.2,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,...,CA,9,Miscellaneous,0.0,28.3,43.3,36.3,14.0,1004.7,0.0
5,20292.0,2013,Riverside,33,2013-08-07,2013-08-12,26.0,33.861570,-116.904270,True,...,CA,14,Unidentified,48.0,12.7,31.1,21.7,8.6,1016.0,NaN
8,11429.0,2013,Tehama,52,2013-08-23,2013-08-29,5.0,40.042630,-121.853970,True,...,CA,9,Miscellaneous,0.0,12.6,26.5,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,4500.0,2018,Solano,48,2018-10-07,2019-01-04,0.0,38.270000,-121.932900,False,...,CA,14,Unidentified,0.0,18.3,27.5,22.4,29.8,1011.5,0.0
1146,293.0,2018,Kern,15,2018-05-16,2019-01-04,0.0,35.342900,-118.729900,False,...,CA,14,Unidentified,0.0,15.0,26.1,20.2,14.4,1015.7,0.0
1147,33.0,2018,Tulare,54,2018-02-18,2019-01-03,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,3.9,21.1,12.3,14.3,1014.6,NaN
1148,0.0,2018,Santa Barbara,"42,56",2018-01-09,2019-01-03,0.0,34.672900,-120.016500,True,...,CA,14,Unidentified,0.0,11.1,17.2,14.0,16.9,NaN,59.4
1149,30.0,2019,Riverside,33,2019-04-09,2019-04-10,0.0,33.743700,-115.993800,False,...,CA,14,Unidentified,0.0,20.0,36.7,26.9,20.3,1009.0,0.0

In [211]:
#Appending the lat_lnf_df with the main df
california_fire = california_fire.append(api_weather_data_df)

In [212]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,...,CA,14,Unidentified,0.0,17.0,36.0,25.8,6.0,NaN,NaN
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,...,CA,14,Unidentified,0.0,16.7,32.2,24.0,36.9,1009.2,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,...,CA,9,Miscellaneous,0.0,28.3,43.3,36.3,14.0,1004.7,0.0
5,20292.0,2013,Riverside,33,2013-08-07,2013-08-12,26.0,33.861570,-116.904270,True,...,CA,14,Unidentified,48.0,12.7,31.1,21.7,8.6,1016.0,NaN
8,11429.0,2013,Tehama,52,2013-08-23,2013-08-29,5.0,40.042630,-121.853970,True,...,CA,9,Miscellaneous,0.0,12.6,26.5,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,80.0,2016,Madera,20,7/21/2016,7/25/2016,0.0,37.218000,-119.762700,True,...,CA,14,Unidentified,0.0,14.0,30.0,26.0,4.0,1014.0,0.0
420,42.0,2016,Lassen,18,7/30/2016,8/1/2016,0.0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0.0,15.0,32.0,28.0,6.0,1010.0,0.0
421,25.0,2016,Lake,17,7/29/2016,7/31/2016,0.0,39.099600,-122.753200,False,...,CA,14,Unidentified,0.0,20.0,40.0,34.0,4.0,1010.0,0.0
422,16031.0,2017,Tulare,54,6/24/2017,1/9/2018,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,21.0,41.0,35.0,4.0,1013.0,0.0
423,21.0,2017,Shasta,45,6/13/2017,1/9/2018,0.0,40.763700,-122.040500,False,...,CA,14,Unidentified,0.0,5.0,26.0,21.0,5.0,1021.0,0.0

In [213]:
california_fire = california_fire.reset_index(drop=True)

In [214]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,...,CA,14,Unidentified,0.0,17.0,36.0,25.8,6.0,NaN,NaN
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,...,CA,14,Unidentified,0.0,16.7,32.2,24.0,36.9,1009.2,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,...,CA,9,Miscellaneous,0.0,28.3,43.3,36.3,14.0,1004.7,0.0
3,20292.0,2013,Riverside,33,2013-08-07,2013-08-12,26.0,33.861570,-116.904270,True,...,CA,14,Unidentified,48.0,12.7,31.1,21.7,8.6,1016.0,NaN
4,11429.0,2013,Tehama,52,2013-08-23,2013-08-29,5.0,40.042630,-121.853970,True,...,CA,9,Miscellaneous,0.0,12.6,26.5,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,80.0,2016,Madera,20,7/21/2016,7/25/2016,0.0,37.218000,-119.762700,True,...,CA,14,Unidentified,0.0,14.0,30.0,26.0,4.0,1014.0,0.0
1146,42.0,2016,Lassen,18,7/30/2016,8/1/2016,0.0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0.0,15.0,32.0,28.0,6.0,1010.0,0.0
1147,25.0,2016,Lake,17,7/29/2016,7/31/2016,0.0,39.099600,-122.753200,False,...,CA,14,Unidentified,0.0,20.0,40.0,34.0,4.0,1010.0,0.0
1148,16031.0,2017,Tulare,54,6/24/2017,1/9/2018,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,21.0,41.0,35.0,4.0,1013.0,0.0
1149,21.0,2017,Shasta,45,6/13/2017,1/9/2018,0.0,40.763700,-122.040500,False,...,CA,14,Unidentified,0.0,5.0,26.0,21.0,5.0,1021.0,0.0

In [215]:
california_fire[(california_fire['Minimum_Temp'] == 0) & (california_fire['Maximum_Temp'] == 0) &
                                    (california_fire['Wind_Speed'] == 1) & (california_fire['Air_Pressure'] == 1) &
                                    (california_fire['Precipitation'] == 0) & (california_fire['Average_Temp'] == 0)]

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
795,120.0,2014,Calaveras,5,6/20/2014,6/21/2014,0.0,120.679019,38.178241,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
799,70.0,2014,Solano,48,6/12/2014,6/13/2014,0.0,121.999000,38.453000,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0
870,95.0,2016,San Benito,35,7/9/2016,7/10/2016,0.0,5487.000000,-120.841536,False,...,CA,9,Miscellaneous,0.0,0.0,0.0,0.0,1.0,1.0,0.0
945,85.0,2017,Riverside,33,8/31/2017,1/9/2018,0.0,117.337331,34.015742,False,...,CA,14,Unidentified,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [216]:
california_fire.isnull().sum()

Total_Acres_Burned          0
Archive_Year                0
County_Name                 0
County_ID                   0
Fire_Started_Date           0
Fire_Extinguished_Date      0
Injuries                    0
Latitude                    0
Longitude                   0
Major_Incident              0
Location                    0
Fire_Name                   0
Percent_Contained           0
State                       0
Cause_id                    0
Cause_Description           0
Structure_Impacted          0
Minimum_Temp                3
Maximum_Temp                4
Average_Temp               51
Wind_Speed                 82
Air_Pressure              175
Precipitation             141
dtype: int64

In [217]:
# Fill null Wind_Speed, Air_pressure, Precipitation with 0 to avoid dropping them.
california_fire['Wind_Speed'] = california_fire['Wind_Speed'].fillna(0)
california_fire['Air_Pressure'] = california_fire['Air_Pressure'].fillna(0)
california_fire['Precipitation'] = california_fire['Precipitation'].fillna(0)

In [218]:
california_fire.dropna(subset=['Minimum_Temp', 'Maximum_Temp', 'Average_Temp', 'Wind_Speed','Air_Pressure','Precipitation'], inplace=True)

In [219]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,...,CA,14,Unidentified,0.0,17.0,36.0,25.8,6.0,0.0,0.0
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,...,CA,14,Unidentified,0.0,16.7,32.2,24.0,36.9,1009.2,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,...,CA,9,Miscellaneous,0.0,28.3,43.3,36.3,14.0,1004.7,0.0
3,20292.0,2013,Riverside,33,2013-08-07,2013-08-12,26.0,33.861570,-116.904270,True,...,CA,14,Unidentified,48.0,12.7,31.1,21.7,8.6,1016.0,0.0
5,8073.0,2013,Shasta,45,2013-09-09,2013-09-15,6.0,40.498332,-122.535496,True,...,CA,7,Arson,211.0,20.0,41.1,31.3,16.2,1006.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,80.0,2016,Madera,20,7/21/2016,7/25/2016,0.0,37.218000,-119.762700,True,...,CA,14,Unidentified,0.0,14.0,30.0,26.0,4.0,1014.0,0.0
1146,42.0,2016,Lassen,18,7/30/2016,8/1/2016,0.0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0.0,15.0,32.0,28.0,6.0,1010.0,0.0
1147,25.0,2016,Lake,17,7/29/2016,7/31/2016,0.0,39.099600,-122.753200,False,...,CA,14,Unidentified,0.0,20.0,40.0,34.0,4.0,1010.0,0.0
1148,16031.0,2017,Tulare,54,6/24/2017,1/9/2018,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,21.0,41.0,35.0,4.0,1013.0,0.0
1149,21.0,2017,Shasta,45,6/13/2017,1/9/2018,0.0,40.763700,-122.040500,False,...,CA,14,Unidentified,0.0,5.0,26.0,21.0,5.0,1021.0,0.0

In [220]:
fire_locations = california_fire[["Fire_Name", "County_ID", "County_Name", "Location", "Latitude", "Longitude", "Minimum_Temp", "Maximum_Temp", "Average_Temp","Wind_Speed","Air_Pressure","Precipitation"]]
fire_locations.columns = map(str.lower, fire_locations.columns)

In [228]:
california_fire.isnull().sum()

Total_Acres_Burned        0
Archive_Year              0
County_Name               0
County_ID                 0
Fire_Started_Date         0
Fire_Extinguished_Date    0
Injuries                  0
Latitude                  0
Longitude                 0
Major_Incident            0
Location                  0
Fire_Name                 0
Percent_Contained         0
State                     0
Cause_id                  0
Cause_Description         0
Structure_Impacted        0
Minimum_Temp              0
Maximum_Temp              0
Average_Temp              0
Wind_Speed                0
Air_Pressure              0
Precipitation             0
dtype: int64

In [229]:
california_fire

,Total_Acres_Burned,Archive_Year,County_Name,County_ID,Fire_Started_Date,Fire_Extinguished_Date,Injuries,Latitude,Longitude,Major_Incident,...,State,Cause_id,Cause_Description,Structure_Impacted,Minimum_Temp,Maximum_Temp,Average_Temp,Wind_Speed,Air_Pressure,Precipitation
0,257314.0,2013,Tuolumne,55,2013-08-17,2013-09-06,0.0,37.857000,-120.086000,False,...,CA,14,Unidentified,0.0,17.0,36.0,25.8,6.0,0.0,0.0
1,30274.0,2013,Los Angeles,19,2013-05-30,2013-06-08,0.0,34.585595,-118.423176,False,...,CA,14,Unidentified,0.0,16.7,32.2,24.0,36.9,1009.2,0.0
2,27531.0,2013,Riverside,33,2013-07-15,2013-07-30,0.0,33.709500,-116.728850,False,...,CA,9,Miscellaneous,0.0,28.3,43.3,36.3,14.0,1004.7,0.0
3,20292.0,2013,Riverside,33,2013-08-07,2013-08-12,26.0,33.861570,-116.904270,True,...,CA,14,Unidentified,48.0,12.7,31.1,21.7,8.6,1016.0,0.0
5,8073.0,2013,Shasta,45,2013-09-09,2013-09-15,6.0,40.498332,-122.535496,True,...,CA,7,Arson,211.0,20.0,41.1,31.3,16.2,1006.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1145,80.0,2016,Madera,20,7/21/2016,7/25/2016,0.0,37.218000,-119.762700,True,...,CA,14,Unidentified,0.0,14.0,30.0,26.0,4.0,1014.0,0.0
1146,42.0,2016,Lassen,18,7/30/2016,8/1/2016,0.0,40.673600,-120.594300,True,...,CA,2,Equipment Use,0.0,15.0,32.0,28.0,6.0,1010.0,0.0
1147,25.0,2016,Lake,17,7/29/2016,7/31/2016,0.0,39.099600,-122.753200,False,...,CA,14,Unidentified,0.0,20.0,40.0,34.0,4.0,1010.0,0.0
1148,16031.0,2017,Tulare,54,6/24/2017,1/9/2018,0.0,36.220100,-118.800500,False,...,CA,14,Unidentified,0.0,21.0,41.0,35.0,4.0,1013.0,0.0
1149,21.0,2017,Shasta,45,6/13/2017,1/9/2018,0.0,40.763700,-122.040500,False,...,CA,14,Unidentified,0.0,5.0,26.0,21.0,5.0,1021.0,0.0

In [230]:
statistical_description = california_fire[['Total_Acres_Burned','Injuries','Structure_Impacted','Maximum_Temp','Wind_Speed','Precipitation']].describe()

In [231]:
statistical_description = statistical_description.rename(columns={'Maximum_Temp':'Maximum_Temp(°C)',
                                                  'Wind_Speed':'Wind_Speed(km/hr)',
                                                     'Precipitation':'Precipitation(%)'})
statistical_description

,Total_Acres_Burned,Injuries,Structure_Impacted,Maximum_Temp(°C),Wind_Speed(km/hr),Precipitation(%)
count,1098.000000,1098.000000,1098.000000,1098.000000,1098.000000,1098.000000
mean,4163.568306,0.285974,23.523679,30.276776,9.352459,0.094718
std,21868.284179,1.553719,234.897402,6.853777,5.888618,1.844218
min,0.000000,0.000000,0.000000,-0.500000,0.000000,0.000000
25%,38.000000,0.000000,0.000000,26.000000,5.000000,0.000000
50%,102.500000,0.000000,0.000000,31.000000,8.650000,0.000000
75%,490.750000,0.000000,0.000000,35.000000,11.975000,0.000000
max,410203.000000,26.000000,5953.000000,49.400000,36.900000,59.400000

In [97]:
# Connect Pandas to SQL.
from sqlalchemy import create_engine
from config import db_password
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/wildfire_db"
engine = create_engine(db_string)
fire_cause.to_sql(name='fire_cause', con=engine, if_exists='append', index=False)
fire_incidents.to_sql(name='fire_incidents', con=engine, if_exists='append', index=False)
fire_impacts.to_sql(name='fire_impacts', con=engine, if_exists='append', index=False)
fire_locations.to_sql(name='fire_locations', con=engine, if_exists='append', index=False)